# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List
from reacon_sdk.models.airtable_mapping_options_response_options_bases_inner import AirtableMappingOptionsResponseOptionsBasesInner
from reacon_sdk.models.airtable_mapping_options_response_options_tables_inner import AirtableMappingOptionsResponseOptionsTablesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AirtableMappingOptionsResponseOptions(BaseModel):
    """
    AirtableMappingOptionsResponseOptions
    """ # noqa: E501
    bases: List[AirtableMappingOptionsResponseOptionsBasesInner]
    provider: StrictStr
    tables: List[AirtableMappingOptionsResponseOptionsTablesInner]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["bases", "provider", "tables"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AirtableMappingOptionsResponseOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bases (list)
        _items = []
        if self.bases:
            for _item_bases in self.bases:
                _items.append(_item_bases.to_dict() if _item_bases is not None else None)
            _dict['bases'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tables (list)
        _items = []
        if self.tables:
            for _item_tables in self.tables:
                _items.append(_item_tables.to_dict() if _item_tables is not None else None)
            _dict['tables'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AirtableMappingOptionsResponseOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "bases": [AirtableMappingOptionsResponseOptionsBasesInner.from_dict(_item) for _item in obj["bases"]] if obj.get("bases") is not None else None,
            "provider": obj.get("provider"),
            "tables": [AirtableMappingOptionsResponseOptionsTablesInner.from_dict(_item) for _item in obj["tables"]] if obj.get("tables") is not None else None
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


