# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from reacon_sdk.models.batch_verification_request_only_if_free import BatchVerificationRequestOnlyIfFree
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BatchVerificationRequest(BaseModel):
    """
    BatchVerificationRequest
    """ # noqa: E501
    cache_max_age: Optional[StrictStr] = Field(default=None, alias="cacheMaxAge")
    emails: Annotated[List[StrictStr], Field(min_length=1)]
    only_if_free: Optional[BatchVerificationRequestOnlyIfFree] = Field(default=None, alias="onlyIfFree")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["cacheMaxAge", "emails", "onlyIfFree"]

    @field_validator('cache_max_age')
    def cache_max_age_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['live', '1d', '1w', '1m']):
            raise ValueError("must be one of enum values ('live', '1d', '1w', '1m')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BatchVerificationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of only_if_free
        if self.only_if_free:
            _dict['onlyIfFree'] = self.only_if_free.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BatchVerificationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "cacheMaxAge": obj.get("cacheMaxAge"),
            "emails": obj.get("emails"),
            "onlyIfFree": BatchVerificationRequestOnlyIfFree.from_dict(obj["onlyIfFree"]) if obj.get("onlyIfFree") is not None else None
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


