# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BindWebflowFormRequest(BaseModel):
    """
    BindWebflowFormRequest
    """ # noqa: E501
    capability: StrictStr
    connection_id: UUID = Field(alias="connectionId")
    field_mapping: Dict[str, Annotated[str, Field(min_length=1, strict=True, max_length=254)]] = Field(alias="fieldMapping")
    form_id: Annotated[str, Field(min_length=3, strict=True, max_length=100)] = Field(alias="formId")
    __properties: ClassVar[List[str]] = ["capability", "connectionId", "fieldMapping", "formId"]

    @field_validator('capability')
    def capability_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['email.find', 'email.verify', 'domain.search']):
            raise ValueError("must be one of enum values ('email.find', 'email.verify', 'domain.search')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BindWebflowFormRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BindWebflowFormRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "capability": obj.get("capability"),
            "connectionId": obj.get("connectionId"),
            "fieldMapping": obj.get("fieldMapping"),
            "formId": obj.get("formId")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


