# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from reacon_sdk.models.configure_coda_request_mapping import ConfigureCodaRequestMapping
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigureCodaRequest(BaseModel):
    """
    ConfigureCodaRequest
    """ # noqa: E501
    api_token: Annotated[str, Field(min_length=20, strict=True, max_length=16384)] = Field(alias="apiToken")
    doc_id: Annotated[str, Field(min_length=1, strict=True, max_length=200)] = Field(alias="docId")
    label: Annotated[str, Field(min_length=1, strict=True, max_length=120)]
    mapping: ConfigureCodaRequestMapping
    mode: Optional[StrictStr] = None
    table_id: Annotated[str, Field(min_length=1, strict=True, max_length=200)] = Field(alias="tableId")
    __properties: ClassVar[List[str]] = ["apiToken", "docId", "label", "mapping", "mode", "tableId"]

    @field_validator('doc_id', mode="before")
    def doc_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[A-Za-z0-9_-]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9_-]+$/")
        return value

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['live', 'emulated']):
            raise ValueError("must be one of enum values ('live', 'emulated')")
        return value

    @field_validator('table_id', mode="before")
    def table_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[A-Za-z0-9_-]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Za-z0-9_-]+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigureCodaRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of mapping
        if self.mapping:
            _dict['mapping'] = self.mapping.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigureCodaRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "apiToken": obj.get("apiToken"),
            "docId": obj.get("docId"),
            "label": obj.get("label"),
            "mapping": ConfigureCodaRequestMapping.from_dict(obj["mapping"]) if obj.get("mapping") is not None else None,
            "mode": obj.get("mode"),
            "tableId": obj.get("tableId")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


