# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ConfigureCodaRequestMapping(BaseModel):
    """
    ConfigureCodaRequestMapping
    """ # noqa: E501
    company: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    email: Annotated[str, Field(min_length=1, strict=True, max_length=200)]
    first_name: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(default=None, alias="firstName")
    job_title: Optional[Annotated[str, Field(strict=True, max_length=200)]] = Field(default=None, alias="jobTitle")
    last_name: Annotated[str, Field(min_length=1, strict=True, max_length=200)] = Field(alias="lastName")
    local_id: Annotated[str, Field(min_length=1, strict=True, max_length=200)] = Field(alias="localId")
    phone: Optional[Annotated[str, Field(strict=True, max_length=200)]] = None
    __properties: ClassVar[List[str]] = ["company", "email", "firstName", "jobTitle", "lastName", "localId", "phone"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConfigureCodaRequestMapping from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # set to None if company (nullable) is None
        # and model_fields_set contains the field
        if self.company is None and "company" in self.model_fields_set:
            _dict['company'] = None

        # set to None if first_name (nullable) is None
        # and model_fields_set contains the field
        if self.first_name is None and "first_name" in self.model_fields_set:
            _dict['firstName'] = None

        # set to None if job_title (nullable) is None
        # and model_fields_set contains the field
        if self.job_title is None and "job_title" in self.model_fields_set:
            _dict['jobTitle'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConfigureCodaRequestMapping from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "company": obj.get("company"),
            "email": obj.get("email"),
            "firstName": obj.get("firstName"),
            "jobTitle": obj.get("jobTitle"),
            "lastName": obj.get("lastName"),
            "localId": obj.get("localId"),
            "phone": obj.get("phone")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


