# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List
from reacon_sdk.models.integration_provider_list_providers_inner_connectability import IntegrationProviderListProvidersInnerConnectability
from reacon_sdk.models.integration_provider_list_providers_inner_readiness import IntegrationProviderListProvidersInnerReadiness
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IntegrationProviderListProvidersInner(BaseModel):
    """
    IntegrationProviderListProvidersInner
    """ # noqa: E501
    auth: StrictStr
    category: StrictStr
    connectability: IntegrationProviderListProvidersInnerConnectability
    implemented: StrictBool
    name: StrictStr
    provider: StrictStr
    readiness: IntegrationProviderListProvidersInnerReadiness
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["auth", "category", "connectability", "implemented", "name", "provider", "readiness"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntegrationProviderListProvidersInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of connectability
        if self.connectability:
            _dict['connectability'] = self.connectability.to_dict()
        # override the default output from pydantic by calling `to_dict()` of readiness
        if self.readiness:
            _dict['readiness'] = self.readiness.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntegrationProviderListProvidersInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "auth": obj.get("auth"),
            "category": obj.get("category"),
            "connectability": IntegrationProviderListProvidersInnerConnectability.from_dict(obj["connectability"]) if obj.get("connectability") is not None else None,
            "implemented": obj.get("implemented"),
            "name": obj.get("name"),
            "provider": obj.get("provider"),
            "readiness": IntegrationProviderListProvidersInnerReadiness.from_dict(obj["readiness"]) if obj.get("readiness") is not None else None
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


