# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from reacon_sdk.models.integration_capability_response_output_non_null import IntegrationCapabilityResponseOutputNonNull
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IntegrationCapabilityResponse(BaseModel):
    """
    IntegrationCapabilityResponse
    """ # noqa: E501
    actual_credits: StrictInt = Field(alias="actualCredits")
    capability: StrictStr = Field(description="Known values: email.find, email.verify, domain.search. Clients preserve future values.")
    charged: StrictBool
    emulated: StrictBool
    estimated_credits: StrictInt = Field(alias="estimatedCredits")
    execution_id: StrictStr = Field(alias="executionId")
    mode: StrictStr = Field(description="Known values: preview, live. Clients preserve future values.")
    output: Optional[IntegrationCapabilityResponseOutputNonNull]
    replay: StrictBool
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["actualCredits", "capability", "charged", "emulated", "estimatedCredits", "executionId", "mode", "output", "replay"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntegrationCapabilityResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of output
        if self.output:
            _dict['output'] = self.output.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        if self.output is None and "output" in self.model_fields_set:
            _dict['output'] = None
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntegrationCapabilityResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "actualCredits": obj.get("actualCredits"),
            "capability": obj.get("capability"),
            "charged": obj.get("charged"),
            "emulated": obj.get("emulated"),
            "estimatedCredits": obj.get("estimatedCredits"),
            "executionId": obj.get("executionId"),
            "mode": obj.get("mode"),
            "output": IntegrationCapabilityResponseOutputNonNull.from_dict(obj["output"]) if obj.get("output") is not None else None,
            "replay": obj.get("replay")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


