# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from reacon_sdk.models.integration_connection_health import IntegrationConnectionHealth
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IntegrationConnection(BaseModel):
    """
    IntegrationConnection
    """ # noqa: E501
    capabilities: Dict[str, Any] = Field(description="Provider-specific capability flags.")
    config: Dict[str, Any] = Field(description="Provider-specific public connection configuration; credentials are stored separately.")
    created_at: StrictStr
    health: IntegrationConnectionHealth
    id: StrictStr
    label: StrictStr
    mode: StrictStr = Field(description="Known values: live, emulated. Clients preserve future values.")
    provider: StrictStr
    provider_account_id: Optional[StrictStr]
    provider_base_url: Optional[StrictStr]
    status: StrictStr = Field(description="Known values: ready, attention, disconnected, paused. Clients preserve future values.")
    team_id: StrictStr
    updated_at: StrictStr
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["capabilities", "config", "created_at", "health", "id", "label", "mode", "provider", "provider_account_id", "provider_base_url", "status", "team_id", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IntegrationConnection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of health
        if self.health:
            _dict['health'] = self.health.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if provider_account_id (nullable) is None
        # and model_fields_set contains the field
        if self.provider_account_id is None and "provider_account_id" in self.model_fields_set:
            _dict['provider_account_id'] = None

        # set to None if provider_base_url (nullable) is None
        # and model_fields_set contains the field
        if self.provider_base_url is None and "provider_base_url" in self.model_fields_set:
            _dict['provider_base_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IntegrationConnection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "capabilities": obj.get("capabilities"),
            "config": obj.get("config"),
            "created_at": obj.get("created_at"),
            "health": IntegrationConnectionHealth.from_dict(obj["health"]) if obj.get("health") is not None else None,
            "id": obj.get("id"),
            "label": obj.get("label"),
            "mode": obj.get("mode"),
            "provider": obj.get("provider"),
            "provider_account_id": obj.get("provider_account_id"),
            "provider_base_url": obj.get("provider_base_url"),
            "status": obj.get("status"),
            "team_id": obj.get("team_id"),
            "updated_at": obj.get("updated_at")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


