# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from reacon_sdk.models.mail_patch_campaigns_by_campaign_id_request_policy_domain_quotas_inner import MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner
from reacon_sdk.models.mail_patch_campaigns_by_campaign_id_request_policy_sending_windows_inner import MailPatchCampaignsByCampaignIdRequestPolicySendingWindowsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailPatchCampaignsByCampaignIdRequestPolicy(BaseModel):
    """
    MailPatchCampaignsByCampaignIdRequestPolicy
    """ # noqa: E501
    domain_quotas: Optional[Annotated[List[MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner], Field(max_length=10)]] = Field(default=None, alias="domainQuotas")
    mailbox_quotas: Optional[Annotated[List[MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner], Field(max_length=10)]] = Field(default=None, alias="mailboxQuotas")
    recipient_cooldown_ms: Optional[Annotated[int, Field(le=31536000000, strict=True, ge=0)]] = Field(default=None, alias="recipientCooldownMs")
    recipient_quotas: Optional[Annotated[List[MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner], Field(max_length=10)]] = Field(default=None, alias="recipientQuotas")
    sending_windows: Optional[Annotated[List[MailPatchCampaignsByCampaignIdRequestPolicySendingWindowsInner], Field(max_length=28)]] = Field(default=None, alias="sendingWindows")
    tenant_quotas: Optional[Annotated[List[MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner], Field(max_length=10)]] = Field(default=None, alias="tenantQuotas")
    time_zone: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = Field(default='UTC', alias="timeZone")
    __properties: ClassVar[List[str]] = ["domainQuotas", "mailboxQuotas", "recipientCooldownMs", "recipientQuotas", "sendingWindows", "tenantQuotas", "timeZone"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailPatchCampaignsByCampaignIdRequestPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in domain_quotas (list)
        _items = []
        if self.domain_quotas:
            for _item_domain_quotas in self.domain_quotas:
                _items.append(_item_domain_quotas.to_dict() if _item_domain_quotas is not None else None)
            _dict['domainQuotas'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in mailbox_quotas (list)
        _items = []
        if self.mailbox_quotas:
            for _item_mailbox_quotas in self.mailbox_quotas:
                _items.append(_item_mailbox_quotas.to_dict() if _item_mailbox_quotas is not None else None)
            _dict['mailboxQuotas'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in recipient_quotas (list)
        _items = []
        if self.recipient_quotas:
            for _item_recipient_quotas in self.recipient_quotas:
                _items.append(_item_recipient_quotas.to_dict() if _item_recipient_quotas is not None else None)
            _dict['recipientQuotas'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sending_windows (list)
        _items = []
        if self.sending_windows:
            for _item_sending_windows in self.sending_windows:
                _items.append(_item_sending_windows.to_dict() if _item_sending_windows is not None else None)
            _dict['sendingWindows'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tenant_quotas (list)
        _items = []
        if self.tenant_quotas:
            for _item_tenant_quotas in self.tenant_quotas:
                _items.append(_item_tenant_quotas.to_dict() if _item_tenant_quotas is not None else None)
            _dict['tenantQuotas'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailPatchCampaignsByCampaignIdRequestPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "domainQuotas": [MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner.from_dict(_item) for _item in obj["domainQuotas"]] if obj.get("domainQuotas") is not None else None,
            "mailboxQuotas": [MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner.from_dict(_item) for _item in obj["mailboxQuotas"]] if obj.get("mailboxQuotas") is not None else None,
            "recipientCooldownMs": obj.get("recipientCooldownMs"),
            "recipientQuotas": [MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner.from_dict(_item) for _item in obj["recipientQuotas"]] if obj.get("recipientQuotas") is not None else None,
            "sendingWindows": [MailPatchCampaignsByCampaignIdRequestPolicySendingWindowsInner.from_dict(_item) for _item in obj["sendingWindows"]] if obj.get("sendingWindows") is not None else None,
            "tenantQuotas": [MailPatchCampaignsByCampaignIdRequestPolicyDomainQuotasInner.from_dict(_item) for _item in obj["tenantQuotas"]] if obj.get("tenantQuotas") is not None else None,
            "timeZone": obj.get("timeZone") if obj.get("timeZone") is not None else 'UTC'
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


