# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from reacon_sdk.models.mail_post_mailboxes_manual_request_imap import MailPostMailboxesManualRequestImap
from reacon_sdk.models.mail_post_mailboxes_manual_request_smtp import MailPostMailboxesManualRequestSmtp
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailPostMailboxesManualRequest(BaseModel):
    """
    MailPostMailboxesManualRequest
    """ # noqa: E501
    daily_limit: Optional[Annotated[int, Field(le=100000, strict=True, gt=0)]] = Field(default=500, alias="dailyLimit")
    email: Annotated[str, Field(strict=True, max_length=320)]
    hourly_limit: Optional[Annotated[int, Field(le=10000, strict=True, gt=0)]] = Field(default=100, alias="hourlyLimit")
    imap: Optional[MailPostMailboxesManualRequestImap] = None
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = None
    ramp_enabled: Optional[StrictBool] = Field(default=False, alias="rampEnabled")
    ramp_interval_hours: Optional[Annotated[int, Field(le=720, strict=True, gt=0)]] = Field(default=24, alias="rampIntervalHours")
    ramp_step: Optional[Annotated[int, Field(le=100000, strict=True, gt=0)]] = Field(default=3, alias="rampStep")
    smtp: MailPostMailboxesManualRequestSmtp
    starting_daily_limit: Optional[Annotated[int, Field(le=100000, strict=True, gt=0)]] = Field(default=3, alias="startingDailyLimit")
    __properties: ClassVar[List[str]] = ["dailyLimit", "email", "hourlyLimit", "imap", "name", "rampEnabled", "rampIntervalHours", "rampStep", "smtp", "startingDailyLimit"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailPostMailboxesManualRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of imap
        if self.imap:
            _dict['imap'] = self.imap.to_dict()
        # override the default output from pydantic by calling `to_dict()` of smtp
        if self.smtp:
            _dict['smtp'] = self.smtp.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailPostMailboxesManualRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "dailyLimit": obj.get("dailyLimit") if obj.get("dailyLimit") is not None else 500,
            "email": obj.get("email"),
            "hourlyLimit": obj.get("hourlyLimit") if obj.get("hourlyLimit") is not None else 100,
            "imap": MailPostMailboxesManualRequestImap.from_dict(obj["imap"]) if obj.get("imap") is not None else None,
            "name": obj.get("name"),
            "rampEnabled": obj.get("rampEnabled") if obj.get("rampEnabled") is not None else False,
            "rampIntervalHours": obj.get("rampIntervalHours") if obj.get("rampIntervalHours") is not None else 24,
            "rampStep": obj.get("rampStep") if obj.get("rampStep") is not None else 3,
            "smtp": MailPostMailboxesManualRequestSmtp.from_dict(obj["smtp"]) if obj.get("smtp") is not None else None,
            "startingDailyLimit": obj.get("startingDailyLimit") if obj.get("startingDailyLimit") is not None else 3
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


