# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from reacon_sdk.models.mail_campaign_progress_message_counts import MailCampaignProgressMessageCounts
from reacon_sdk.models.mail_message_analytics_overview_daily_inner import MailMessageAnalyticsOverviewDailyInner
from reacon_sdk.models.mail_message_analytics_overview_mailboxes_inner import MailMessageAnalyticsOverviewMailboxesInner
from reacon_sdk.models.mail_message_analytics_overview_variants_inner import MailMessageAnalyticsOverviewVariantsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailMessageAnalyticsOverview(BaseModel):
    """
    MailMessageAnalyticsOverview
    """ # noqa: E501
    acceptance_rate: Union[StrictFloat, StrictInt] = Field(alias="acceptanceRate")
    average_acceptance_latency_ms: Optional[Union[StrictFloat, StrictInt]] = Field(alias="averageAcceptanceLatencyMs")
    bounce_rate: Union[StrictFloat, StrictInt] = Field(alias="bounceRate")
    complaint_rate: Union[StrictFloat, StrictInt] = Field(alias="complaintRate")
    counts: MailCampaignProgressMessageCounts
    daily: List[MailMessageAnalyticsOverviewDailyInner]
    delivery_rate: Union[StrictFloat, StrictInt] = Field(alias="deliveryRate")
    var_from: datetime = Field(alias="from")
    mailboxes: List[MailMessageAnalyticsOverviewMailboxesInner]
    reply_rate: Union[StrictFloat, StrictInt] = Field(alias="replyRate")
    to: datetime
    total: Union[StrictFloat, StrictInt]
    variants: List[MailMessageAnalyticsOverviewVariantsInner]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["acceptanceRate", "averageAcceptanceLatencyMs", "bounceRate", "complaintRate", "counts", "daily", "deliveryRate", "from", "mailboxes", "replyRate", "to", "total", "variants"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailMessageAnalyticsOverview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of counts
        if self.counts:
            _dict['counts'] = self.counts.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in daily (list)
        _items = []
        if self.daily:
            for _item_daily in self.daily:
                _items.append(_item_daily.to_dict() if _item_daily is not None else None)
            _dict['daily'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in mailboxes (list)
        _items = []
        if self.mailboxes:
            for _item_mailboxes in self.mailboxes:
                _items.append(_item_mailboxes.to_dict() if _item_mailboxes is not None else None)
            _dict['mailboxes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in variants (list)
        _items = []
        if self.variants:
            for _item_variants in self.variants:
                _items.append(_item_variants.to_dict() if _item_variants is not None else None)
            _dict['variants'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if average_acceptance_latency_ms (nullable) is None
        # and model_fields_set contains the field
        if self.average_acceptance_latency_ms is None and "average_acceptance_latency_ms" in self.model_fields_set:
            _dict['averageAcceptanceLatencyMs'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailMessageAnalyticsOverview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "acceptanceRate": obj.get("acceptanceRate"),
            "averageAcceptanceLatencyMs": obj.get("averageAcceptanceLatencyMs"),
            "bounceRate": obj.get("bounceRate"),
            "complaintRate": obj.get("complaintRate"),
            "counts": MailCampaignProgressMessageCounts.from_dict(obj["counts"]) if obj.get("counts") is not None else None,
            "daily": [MailMessageAnalyticsOverviewDailyInner.from_dict(_item) for _item in obj["daily"]] if obj.get("daily") is not None else None,
            "deliveryRate": obj.get("deliveryRate"),
            "from": obj.get("from"),
            "mailboxes": [MailMessageAnalyticsOverviewMailboxesInner.from_dict(_item) for _item in obj["mailboxes"]] if obj.get("mailboxes") is not None else None,
            "replyRate": obj.get("replyRate"),
            "to": obj.get("to"),
            "total": obj.get("total"),
            "variants": [MailMessageAnalyticsOverviewVariantsInner.from_dict(_item) for _item in obj["variants"]] if obj.get("variants") is not None else None
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


