# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from reacon_sdk.models.mail_post_cadences_request_nodes_inner_any_of import MailPostCadencesRequestNodesInnerAnyOf
from reacon_sdk.models.mail_post_cadences_request_nodes_inner_any_of1 import MailPostCadencesRequestNodesInnerAnyOf1
from reacon_sdk.models.mail_post_cadences_request_nodes_inner_any_of2 import MailPostCadencesRequestNodesInnerAnyOf2
from reacon_sdk.models.mail_post_cadences_request_nodes_inner_any_of3 import MailPostCadencesRequestNodesInnerAnyOf3
from reacon_sdk.models.mail_post_cadences_request_nodes_inner_any_of4 import MailPostCadencesRequestNodesInnerAnyOf4
from reacon_sdk.models.mail_post_cadences_request_nodes_inner_any_of5 import MailPostCadencesRequestNodesInnerAnyOf5
from reacon_sdk.models.mail_post_cadences_request_nodes_inner_any_of6 import MailPostCadencesRequestNodesInnerAnyOf6
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

MAILPOSTCADENCESREQUESTNODESINNER_ANY_OF_SCHEMAS = ["MailPostCadencesRequestNodesInnerAnyOf", "MailPostCadencesRequestNodesInnerAnyOf1", "MailPostCadencesRequestNodesInnerAnyOf2", "MailPostCadencesRequestNodesInnerAnyOf3", "MailPostCadencesRequestNodesInnerAnyOf4", "MailPostCadencesRequestNodesInnerAnyOf5", "MailPostCadencesRequestNodesInnerAnyOf6"]

class MailPostCadencesRequestNodesInner(BaseModel):
    """
    Additional server validation applies; this structural schema does not express every contextual or cross-field rule.
    """

    # data type: MailPostCadencesRequestNodesInnerAnyOf
    anyof_schema_1_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf] = None
    # data type: MailPostCadencesRequestNodesInnerAnyOf1
    anyof_schema_2_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf1] = None
    # data type: MailPostCadencesRequestNodesInnerAnyOf2
    anyof_schema_3_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf2] = None
    # data type: MailPostCadencesRequestNodesInnerAnyOf3
    anyof_schema_4_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf3] = None
    # data type: MailPostCadencesRequestNodesInnerAnyOf4
    anyof_schema_5_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf4] = None
    # data type: MailPostCadencesRequestNodesInnerAnyOf5
    anyof_schema_6_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf5] = None
    # data type: MailPostCadencesRequestNodesInnerAnyOf6
    anyof_schema_7_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf6] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[MailPostCadencesRequestNodesInnerAnyOf, MailPostCadencesRequestNodesInnerAnyOf1, MailPostCadencesRequestNodesInnerAnyOf2, MailPostCadencesRequestNodesInnerAnyOf3, MailPostCadencesRequestNodesInnerAnyOf4, MailPostCadencesRequestNodesInnerAnyOf5, MailPostCadencesRequestNodesInnerAnyOf6]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "MailPostCadencesRequestNodesInnerAnyOf", "MailPostCadencesRequestNodesInnerAnyOf1", "MailPostCadencesRequestNodesInnerAnyOf2", "MailPostCadencesRequestNodesInnerAnyOf3", "MailPostCadencesRequestNodesInnerAnyOf4", "MailPostCadencesRequestNodesInnerAnyOf5", "MailPostCadencesRequestNodesInnerAnyOf6" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = MailPostCadencesRequestNodesInner.model_construct()
        error_messages = []
        # validate data type: MailPostCadencesRequestNodesInnerAnyOf
        if not isinstance(v, MailPostCadencesRequestNodesInnerAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailPostCadencesRequestNodesInnerAnyOf`")
        else:
            return v

        # validate data type: MailPostCadencesRequestNodesInnerAnyOf1
        if not isinstance(v, MailPostCadencesRequestNodesInnerAnyOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailPostCadencesRequestNodesInnerAnyOf1`")
        else:
            return v

        # validate data type: MailPostCadencesRequestNodesInnerAnyOf2
        if not isinstance(v, MailPostCadencesRequestNodesInnerAnyOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailPostCadencesRequestNodesInnerAnyOf2`")
        else:
            return v

        # validate data type: MailPostCadencesRequestNodesInnerAnyOf3
        if not isinstance(v, MailPostCadencesRequestNodesInnerAnyOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailPostCadencesRequestNodesInnerAnyOf3`")
        else:
            return v

        # validate data type: MailPostCadencesRequestNodesInnerAnyOf4
        if not isinstance(v, MailPostCadencesRequestNodesInnerAnyOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailPostCadencesRequestNodesInnerAnyOf4`")
        else:
            return v

        # validate data type: MailPostCadencesRequestNodesInnerAnyOf5
        if not isinstance(v, MailPostCadencesRequestNodesInnerAnyOf5):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailPostCadencesRequestNodesInnerAnyOf5`")
        else:
            return v

        # validate data type: MailPostCadencesRequestNodesInnerAnyOf6
        if not isinstance(v, MailPostCadencesRequestNodesInnerAnyOf6):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailPostCadencesRequestNodesInnerAnyOf6`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in MailPostCadencesRequestNodesInner with anyOf schemas: MailPostCadencesRequestNodesInnerAnyOf, MailPostCadencesRequestNodesInnerAnyOf1, MailPostCadencesRequestNodesInnerAnyOf2, MailPostCadencesRequestNodesInnerAnyOf3, MailPostCadencesRequestNodesInnerAnyOf4, MailPostCadencesRequestNodesInnerAnyOf5, MailPostCadencesRequestNodesInnerAnyOf6. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf] = None
        try:
            instance.actual_instance = MailPostCadencesRequestNodesInnerAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf1] = None
        try:
            instance.actual_instance = MailPostCadencesRequestNodesInnerAnyOf1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf2] = None
        try:
            instance.actual_instance = MailPostCadencesRequestNodesInnerAnyOf2.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf3] = None
        try:
            instance.actual_instance = MailPostCadencesRequestNodesInnerAnyOf3.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf4] = None
        try:
            instance.actual_instance = MailPostCadencesRequestNodesInnerAnyOf4.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_6_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf5] = None
        try:
            instance.actual_instance = MailPostCadencesRequestNodesInnerAnyOf5.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_7_validator: Optional[MailPostCadencesRequestNodesInnerAnyOf6] = None
        try:
            instance.actual_instance = MailPostCadencesRequestNodesInnerAnyOf6.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into MailPostCadencesRequestNodesInner with anyOf schemas: MailPostCadencesRequestNodesInnerAnyOf, MailPostCadencesRequestNodesInnerAnyOf1, MailPostCadencesRequestNodesInnerAnyOf2, MailPostCadencesRequestNodesInnerAnyOf3, MailPostCadencesRequestNodesInnerAnyOf4, MailPostCadencesRequestNodesInnerAnyOf5, MailPostCadencesRequestNodesInnerAnyOf6. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], MailPostCadencesRequestNodesInnerAnyOf, MailPostCadencesRequestNodesInnerAnyOf1, MailPostCadencesRequestNodesInnerAnyOf2, MailPostCadencesRequestNodesInnerAnyOf3, MailPostCadencesRequestNodesInnerAnyOf4, MailPostCadencesRequestNodesInnerAnyOf5, MailPostCadencesRequestNodesInnerAnyOf6]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


