# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from reacon_sdk.models.mail_conversation_entry import MailConversationEntry
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailConversationThread(BaseModel):
    """
    MailConversationThread
    """ # noqa: E501
    entries: List[MailConversationEntry]
    id: StrictStr
    latest_at: datetime = Field(alias="latestAt")
    latest_direction: StrictStr = Field(alias="latestDirection")
    latest_status: StrictStr = Field(alias="latestStatus")
    mailbox_id: StrictStr = Field(alias="mailboxId")
    participants: List[StrictStr]
    subject: StrictStr
    unread_count: Union[StrictFloat, StrictInt] = Field(alias="unreadCount")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["entries", "id", "latestAt", "latestDirection", "latestStatus", "mailboxId", "participants", "subject", "unreadCount"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailConversationThread from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in entries (list)
        _items = []
        if self.entries:
            for _item_entries in self.entries:
                _items.append(_item_entries.to_dict() if _item_entries is not None else None)
            _dict['entries'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailConversationThread from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "entries": [MailConversationEntry.from_dict(_item) for _item in obj["entries"]] if obj.get("entries") is not None else None,
            "id": obj.get("id"),
            "latestAt": obj.get("latestAt"),
            "latestDirection": obj.get("latestDirection"),
            "latestStatus": obj.get("latestStatus"),
            "mailboxId": obj.get("mailboxId"),
            "participants": obj.get("participants"),
            "subject": obj.get("subject"),
            "unreadCount": obj.get("unreadCount")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


