# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailPostMailboxesManualRequestImap(BaseModel):
    """
    MailPostMailboxesManualRequestImap
    """ # noqa: E501
    host: Annotated[str, Field(min_length=1, strict=True, max_length=253)]
    mailbox_paths: Optional[Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=500)]], Field(max_length=20)]] = Field(default=None, alias="mailboxPaths")
    password: Annotated[str, Field(min_length=1, strict=True, max_length=4096)]
    port: Annotated[int, Field(le=65535, strict=True, ge=1)] = Field(description="Additional server validation applies; this structural schema does not express every contextual or cross-field rule.")
    security: StrictStr
    server_name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=253)]] = Field(default=None, alias="serverName")
    tls_ca: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100000)]] = Field(default=None, alias="tlsCa")
    username: Annotated[str, Field(min_length=1, strict=True, max_length=500)]
    __properties: ClassVar[List[str]] = ["host", "mailboxPaths", "password", "port", "security", "serverName", "tlsCa", "username"]

    @field_validator('security')
    def security_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['tls', 'starttls', 'plain']):
            raise ValueError("must be one of enum values ('tls', 'starttls', 'plain')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailPostMailboxesManualRequestImap from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailPostMailboxesManualRequestImap from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "host": obj.get("host"),
            "mailboxPaths": obj.get("mailboxPaths"),
            "password": obj.get("password"),
            "port": obj.get("port"),
            "security": obj.get("security"),
            "serverName": obj.get("serverName"),
            "tlsCa": obj.get("tlsCa"),
            "username": obj.get("username")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


