# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from reacon_sdk.models.mail_patch_campaigns_by_campaign_id_request_policy import MailPatchCampaignsByCampaignIdRequestPolicy
from reacon_sdk.models.mail_patch_campaigns_by_campaign_id_request_steps_inner import MailPatchCampaignsByCampaignIdRequestStepsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailPatchCampaignsByCampaignIdRequest(BaseModel):
    """
    MailPatchCampaignsByCampaignIdRequest
    """ # noqa: E501
    audience_list_ids: Optional[Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=200)]], Field(max_length=100)]] = Field(default=None, alias="audienceListIds")
    expected_version: Annotated[int, Field(strict=True, gt=0)] = Field(alias="expectedVersion")
    mailbox_ids: Optional[Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=200)]], Field(max_length=100)]] = Field(default=None, alias="mailboxIds")
    mailbox_pool_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=200)]] = Field(default=None, alias="mailboxPoolId")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=200)]
    policy: Optional[MailPatchCampaignsByCampaignIdRequestPolicy] = None
    scheduled_at: Optional[datetime] = Field(default=None, alias="scheduledAt")
    steps: Optional[Annotated[List[MailPatchCampaignsByCampaignIdRequestStepsInner], Field(max_length=50)]] = None
    __properties: ClassVar[List[str]] = ["audienceListIds", "expectedVersion", "mailboxIds", "mailboxPoolId", "name", "policy", "scheduledAt", "steps"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailPatchCampaignsByCampaignIdRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in steps (list)
        _items = []
        if self.steps:
            for _item_steps in self.steps:
                _items.append(_item_steps.to_dict() if _item_steps is not None else None)
            _dict['steps'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailPatchCampaignsByCampaignIdRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "audienceListIds": obj.get("audienceListIds"),
            "expectedVersion": obj.get("expectedVersion"),
            "mailboxIds": obj.get("mailboxIds"),
            "mailboxPoolId": obj.get("mailboxPoolId"),
            "name": obj.get("name"),
            "policy": MailPatchCampaignsByCampaignIdRequestPolicy.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "scheduledAt": obj.get("scheduledAt"),
            "steps": [MailPatchCampaignsByCampaignIdRequestStepsInner.from_dict(_item) for _item in obj["steps"]] if obj.get("steps") is not None else None
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


