# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from reacon_sdk.models.mail_mail_address import MailMailAddress
from reacon_sdk.models.mail_message_policy import MailMessagePolicy
from reacon_sdk.models.mail_provider_failure import MailProviderFailure
from reacon_sdk.models.mail_rendered_message import MailRenderedMessage
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailMessageRecord(BaseModel):
    """
    MailMessageRecord
    """ # noqa: E501
    accepted_at: Optional[datetime] = Field(default=None, alias="acceptedAt")
    attempt_count: Union[StrictFloat, StrictInt] = Field(alias="attemptCount")
    bcc: List[MailMailAddress]
    cc: List[MailMailAddress]
    created_at: datetime = Field(alias="createdAt")
    id: StrictStr
    idempotency_key: StrictStr = Field(alias="idempotencyKey")
    internet_message_id: Optional[StrictStr] = Field(default=None, alias="internetMessageId")
    last_error: Optional[MailProviderFailure] = Field(default=None, alias="lastError")
    lease_expires_at: Optional[datetime] = Field(default=None, alias="leaseExpiresAt")
    lease_owner: Optional[StrictStr] = Field(default=None, alias="leaseOwner")
    mailbox_id: StrictStr = Field(alias="mailboxId")
    metadata: Dict[str, Any]
    next_attempt_at: datetime = Field(alias="nextAttemptAt")
    parent_message_id: Optional[StrictStr] = Field(default=None, alias="parentMessageId")
    policy: MailMessagePolicy
    provider_message_id: Optional[StrictStr] = Field(default=None, alias="providerMessageId")
    provider_thread_id: Optional[StrictStr] = Field(default=None, alias="providerThreadId")
    rendered: MailRenderedMessage
    reply_to: MailMailAddress = Field(alias="replyTo")
    scheduled_at: datetime = Field(alias="scheduledAt")
    sequence_run_id: Optional[StrictStr] = Field(default=None, alias="sequenceRunId")
    sequence_step_index: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="sequenceStepIndex")
    status: StrictStr
    tenant_id: StrictStr = Field(alias="tenantId")
    to: List[MailMailAddress]
    updated_at: datetime = Field(alias="updatedAt")
    variant_id: Optional[StrictStr] = Field(default=None, alias="variantId")
    version: Union[StrictFloat, StrictInt]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["acceptedAt", "attemptCount", "bcc", "cc", "createdAt", "id", "idempotencyKey", "internetMessageId", "lastError", "leaseExpiresAt", "leaseOwner", "mailboxId", "metadata", "nextAttemptAt", "parentMessageId", "policy", "providerMessageId", "providerThreadId", "rendered", "replyTo", "scheduledAt", "sequenceRunId", "sequenceStepIndex", "status", "tenantId", "to", "updatedAt", "variantId", "version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailMessageRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bcc (list)
        _items = []
        if self.bcc:
            for _item_bcc in self.bcc:
                _items.append(_item_bcc.to_dict() if _item_bcc is not None else None)
            _dict['bcc'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cc (list)
        _items = []
        if self.cc:
            for _item_cc in self.cc:
                _items.append(_item_cc.to_dict() if _item_cc is not None else None)
            _dict['cc'] = _items
        # override the default output from pydantic by calling `to_dict()` of last_error
        if self.last_error:
            _dict['lastError'] = self.last_error.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rendered
        if self.rendered:
            _dict['rendered'] = self.rendered.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reply_to
        if self.reply_to:
            _dict['replyTo'] = self.reply_to.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in to (list)
        _items = []
        if self.to:
            for _item_to in self.to:
                _items.append(_item_to.to_dict() if _item_to is not None else None)
            _dict['to'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailMessageRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "acceptedAt": obj.get("acceptedAt"),
            "attemptCount": obj.get("attemptCount"),
            "bcc": [MailMailAddress.from_dict(_item) for _item in obj["bcc"]] if obj.get("bcc") is not None else None,
            "cc": [MailMailAddress.from_dict(_item) for _item in obj["cc"]] if obj.get("cc") is not None else None,
            "createdAt": obj.get("createdAt"),
            "id": obj.get("id"),
            "idempotencyKey": obj.get("idempotencyKey"),
            "internetMessageId": obj.get("internetMessageId"),
            "lastError": MailProviderFailure.from_dict(obj["lastError"]) if obj.get("lastError") is not None else None,
            "leaseExpiresAt": obj.get("leaseExpiresAt"),
            "leaseOwner": obj.get("leaseOwner"),
            "mailboxId": obj.get("mailboxId"),
            "metadata": obj.get("metadata"),
            "nextAttemptAt": obj.get("nextAttemptAt"),
            "parentMessageId": obj.get("parentMessageId"),
            "policy": MailMessagePolicy.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "providerMessageId": obj.get("providerMessageId"),
            "providerThreadId": obj.get("providerThreadId"),
            "rendered": MailRenderedMessage.from_dict(obj["rendered"]) if obj.get("rendered") is not None else None,
            "replyTo": MailMailAddress.from_dict(obj["replyTo"]) if obj.get("replyTo") is not None else None,
            "scheduledAt": obj.get("scheduledAt"),
            "sequenceRunId": obj.get("sequenceRunId"),
            "sequenceStepIndex": obj.get("sequenceStepIndex"),
            "status": obj.get("status"),
            "tenantId": obj.get("tenantId"),
            "to": [MailMailAddress.from_dict(_item) for _item in obj["to"]] if obj.get("to") is not None else None,
            "updatedAt": obj.get("updatedAt"),
            "variantId": obj.get("variantId"),
            "version": obj.get("version")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


