# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from reacon_sdk.models.mail_webhook_event_snapshot import MailWebhookEventSnapshot
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailWebhookDelivery(BaseModel):
    """
    MailWebhookDelivery
    """ # noqa: E501
    attempt_count: Union[StrictFloat, StrictInt] = Field(alias="attemptCount")
    created_at: datetime = Field(alias="createdAt")
    dead_lettered_at: Optional[datetime] = Field(default=None, alias="deadLetteredAt")
    deduplication_key: StrictStr = Field(alias="deduplicationKey")
    event: MailWebhookEventSnapshot
    id: StrictStr
    last_error_code: Optional[StrictStr] = Field(default=None, alias="lastErrorCode")
    last_error_message: Optional[StrictStr] = Field(default=None, alias="lastErrorMessage")
    lease_expires_at: Optional[datetime] = Field(default=None, alias="leaseExpiresAt")
    lease_owner: Optional[StrictStr] = Field(default=None, alias="leaseOwner")
    next_attempt_at: datetime = Field(alias="nextAttemptAt")
    replay_of: Optional[StrictStr] = Field(default=None, alias="replayOf")
    response_status: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="responseStatus")
    status: StrictStr
    subscription_id: StrictStr = Field(alias="subscriptionId")
    succeeded_at: Optional[datetime] = Field(default=None, alias="succeededAt")
    tenant_id: StrictStr = Field(alias="tenantId")
    updated_at: datetime = Field(alias="updatedAt")
    version: Union[StrictFloat, StrictInt]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["attemptCount", "createdAt", "deadLetteredAt", "deduplicationKey", "event", "id", "lastErrorCode", "lastErrorMessage", "leaseExpiresAt", "leaseOwner", "nextAttemptAt", "replayOf", "responseStatus", "status", "subscriptionId", "succeededAt", "tenantId", "updatedAt", "version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailWebhookDelivery from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of event
        if self.event:
            _dict['event'] = self.event.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailWebhookDelivery from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "attemptCount": obj.get("attemptCount"),
            "createdAt": obj.get("createdAt"),
            "deadLetteredAt": obj.get("deadLetteredAt"),
            "deduplicationKey": obj.get("deduplicationKey"),
            "event": MailWebhookEventSnapshot.from_dict(obj["event"]) if obj.get("event") is not None else None,
            "id": obj.get("id"),
            "lastErrorCode": obj.get("lastErrorCode"),
            "lastErrorMessage": obj.get("lastErrorMessage"),
            "leaseExpiresAt": obj.get("leaseExpiresAt"),
            "leaseOwner": obj.get("leaseOwner"),
            "nextAttemptAt": obj.get("nextAttemptAt"),
            "replayOf": obj.get("replayOf"),
            "responseStatus": obj.get("responseStatus"),
            "status": obj.get("status"),
            "subscriptionId": obj.get("subscriptionId"),
            "succeededAt": obj.get("succeededAt"),
            "tenantId": obj.get("tenantId"),
            "updatedAt": obj.get("updatedAt"),
            "version": obj.get("version")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


