# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from reacon_sdk.models.mail_post_templates_request_whatsapp_approval import MailPostTemplatesRequestWhatsappApproval
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailPostTemplatesRequest(BaseModel):
    """
    MailPostTemplatesRequest
    """ # noqa: E501
    body: Annotated[str, Field(min_length=1, strict=True, max_length=200000)]
    channel: StrictStr
    id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=200)]] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=200)]
    status: StrictStr
    subject: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=998)]] = None
    whatsapp_approval: Optional[MailPostTemplatesRequestWhatsappApproval] = Field(default=None, alias="whatsappApproval")
    __properties: ClassVar[List[str]] = ["body", "channel", "id", "name", "status", "subject", "whatsappApproval"]

    @field_validator('channel')
    def channel_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['email', 'sms', 'whatsapp']):
            raise ValueError("must be one of enum values ('email', 'sms', 'whatsapp')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['draft', 'published', 'archived']):
            raise ValueError("must be one of enum values ('draft', 'published', 'archived')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailPostTemplatesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of whatsapp_approval
        if self.whatsapp_approval:
            _dict['whatsappApproval'] = self.whatsapp_approval.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailPostTemplatesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "body": obj.get("body"),
            "channel": obj.get("channel"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "subject": obj.get("subject"),
            "whatsappApproval": MailPostTemplatesRequestWhatsappApproval.from_dict(obj["whatsappApproval"]) if obj.get("whatsappApproval") is not None else None
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


