# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from reacon_sdk.models.mail_cadence_node_any_of import MailCadenceNodeAnyOf
from reacon_sdk.models.mail_cadence_node_any_of1 import MailCadenceNodeAnyOf1
from reacon_sdk.models.mail_cadence_node_any_of2 import MailCadenceNodeAnyOf2
from reacon_sdk.models.mail_cadence_node_any_of3 import MailCadenceNodeAnyOf3
from reacon_sdk.models.mail_cadence_node_any_of4 import MailCadenceNodeAnyOf4
from reacon_sdk.models.mail_cadence_node_any_of5 import MailCadenceNodeAnyOf5
from reacon_sdk.models.mail_cadence_node_any_of6 import MailCadenceNodeAnyOf6
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

MAILCADENCENODE_ANY_OF_SCHEMAS = ["MailCadenceNodeAnyOf", "MailCadenceNodeAnyOf1", "MailCadenceNodeAnyOf2", "MailCadenceNodeAnyOf3", "MailCadenceNodeAnyOf4", "MailCadenceNodeAnyOf5", "MailCadenceNodeAnyOf6"]

class MailCadenceNode(BaseModel):
    """
    MailCadenceNode
    """

    # data type: MailCadenceNodeAnyOf
    anyof_schema_1_validator: Optional[MailCadenceNodeAnyOf] = None
    # data type: MailCadenceNodeAnyOf1
    anyof_schema_2_validator: Optional[MailCadenceNodeAnyOf1] = None
    # data type: MailCadenceNodeAnyOf2
    anyof_schema_3_validator: Optional[MailCadenceNodeAnyOf2] = None
    # data type: MailCadenceNodeAnyOf3
    anyof_schema_4_validator: Optional[MailCadenceNodeAnyOf3] = None
    # data type: MailCadenceNodeAnyOf4
    anyof_schema_5_validator: Optional[MailCadenceNodeAnyOf4] = None
    # data type: MailCadenceNodeAnyOf5
    anyof_schema_6_validator: Optional[MailCadenceNodeAnyOf5] = None
    # data type: MailCadenceNodeAnyOf6
    anyof_schema_7_validator: Optional[MailCadenceNodeAnyOf6] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[MailCadenceNodeAnyOf, MailCadenceNodeAnyOf1, MailCadenceNodeAnyOf2, MailCadenceNodeAnyOf3, MailCadenceNodeAnyOf4, MailCadenceNodeAnyOf5, MailCadenceNodeAnyOf6]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "MailCadenceNodeAnyOf", "MailCadenceNodeAnyOf1", "MailCadenceNodeAnyOf2", "MailCadenceNodeAnyOf3", "MailCadenceNodeAnyOf4", "MailCadenceNodeAnyOf5", "MailCadenceNodeAnyOf6" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = MailCadenceNode.model_construct()
        error_messages = []
        # validate data type: MailCadenceNodeAnyOf
        if not isinstance(v, MailCadenceNodeAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailCadenceNodeAnyOf`")
        else:
            return v

        # validate data type: MailCadenceNodeAnyOf1
        if not isinstance(v, MailCadenceNodeAnyOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailCadenceNodeAnyOf1`")
        else:
            return v

        # validate data type: MailCadenceNodeAnyOf2
        if not isinstance(v, MailCadenceNodeAnyOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailCadenceNodeAnyOf2`")
        else:
            return v

        # validate data type: MailCadenceNodeAnyOf3
        if not isinstance(v, MailCadenceNodeAnyOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailCadenceNodeAnyOf3`")
        else:
            return v

        # validate data type: MailCadenceNodeAnyOf4
        if not isinstance(v, MailCadenceNodeAnyOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailCadenceNodeAnyOf4`")
        else:
            return v

        # validate data type: MailCadenceNodeAnyOf5
        if not isinstance(v, MailCadenceNodeAnyOf5):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailCadenceNodeAnyOf5`")
        else:
            return v

        # validate data type: MailCadenceNodeAnyOf6
        if not isinstance(v, MailCadenceNodeAnyOf6):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MailCadenceNodeAnyOf6`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in MailCadenceNode with anyOf schemas: MailCadenceNodeAnyOf, MailCadenceNodeAnyOf1, MailCadenceNodeAnyOf2, MailCadenceNodeAnyOf3, MailCadenceNodeAnyOf4, MailCadenceNodeAnyOf5, MailCadenceNodeAnyOf6. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[MailCadenceNodeAnyOf] = None
        try:
            instance.actual_instance = MailCadenceNodeAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[MailCadenceNodeAnyOf1] = None
        try:
            instance.actual_instance = MailCadenceNodeAnyOf1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[MailCadenceNodeAnyOf2] = None
        try:
            instance.actual_instance = MailCadenceNodeAnyOf2.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[MailCadenceNodeAnyOf3] = None
        try:
            instance.actual_instance = MailCadenceNodeAnyOf3.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[MailCadenceNodeAnyOf4] = None
        try:
            instance.actual_instance = MailCadenceNodeAnyOf4.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_6_validator: Optional[MailCadenceNodeAnyOf5] = None
        try:
            instance.actual_instance = MailCadenceNodeAnyOf5.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_7_validator: Optional[MailCadenceNodeAnyOf6] = None
        try:
            instance.actual_instance = MailCadenceNodeAnyOf6.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into MailCadenceNode with anyOf schemas: MailCadenceNodeAnyOf, MailCadenceNodeAnyOf1, MailCadenceNodeAnyOf2, MailCadenceNodeAnyOf3, MailCadenceNodeAnyOf4, MailCadenceNodeAnyOf5, MailCadenceNodeAnyOf6. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], MailCadenceNodeAnyOf, MailCadenceNodeAnyOf1, MailCadenceNodeAnyOf2, MailCadenceNodeAnyOf3, MailCadenceNodeAnyOf4, MailCadenceNodeAnyOf5, MailCadenceNodeAnyOf6]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


