# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from reacon_sdk.models.mail_campaign_draft_step import MailCampaignDraftStep
from reacon_sdk.models.mail_message_policy_input import MailMessagePolicyInput
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailCampaignDraftRecord(BaseModel):
    """
    MailCampaignDraftRecord
    """ # noqa: E501
    audience_list_ids: List[StrictStr] = Field(alias="audienceListIds")
    created_at: datetime = Field(alias="createdAt")
    id: StrictStr
    launched_at: Optional[datetime] = Field(default=None, alias="launchedAt")
    mailbox_ids: List[StrictStr] = Field(alias="mailboxIds")
    mailbox_pool_id: Optional[StrictStr] = Field(default=None, alias="mailboxPoolId")
    name: StrictStr
    policy: MailMessagePolicyInput
    scheduled_at: Optional[datetime] = Field(default=None, alias="scheduledAt")
    status: StrictStr
    steps: List[MailCampaignDraftStep]
    tenant_id: StrictStr = Field(alias="tenantId")
    updated_at: datetime = Field(alias="updatedAt")
    version: Union[StrictFloat, StrictInt]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["audienceListIds", "createdAt", "id", "launchedAt", "mailboxIds", "mailboxPoolId", "name", "policy", "scheduledAt", "status", "steps", "tenantId", "updatedAt", "version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailCampaignDraftRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in steps (list)
        _items = []
        if self.steps:
            for _item_steps in self.steps:
                _items.append(_item_steps.to_dict() if _item_steps is not None else None)
            _dict['steps'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailCampaignDraftRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "audienceListIds": obj.get("audienceListIds"),
            "createdAt": obj.get("createdAt"),
            "id": obj.get("id"),
            "launchedAt": obj.get("launchedAt"),
            "mailboxIds": obj.get("mailboxIds"),
            "mailboxPoolId": obj.get("mailboxPoolId"),
            "name": obj.get("name"),
            "policy": MailMessagePolicyInput.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "scheduledAt": obj.get("scheduledAt"),
            "status": obj.get("status"),
            "steps": [MailCampaignDraftStep.from_dict(_item) for _item in obj["steps"]] if obj.get("steps") is not None else None,
            "tenantId": obj.get("tenantId"),
            "updatedAt": obj.get("updatedAt"),
            "version": obj.get("version")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


