# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailPostCadencesRequestNodesInnerAnyOf3(BaseModel):
    """
    MailPostCadencesRequestNodesInnerAnyOf3
    """ # noqa: E501
    id: Annotated[str, Field(strict=True)]
    kind: StrictStr
    name: Annotated[str, Field(min_length=1, strict=True, max_length=160)]
    next_node_id: Annotated[str, Field(strict=True)] = Field(alias="nextNodeId")
    task_type: StrictStr = Field(alias="taskType")
    title: Annotated[str, Field(min_length=1, strict=True, max_length=500)]
    __properties: ClassVar[List[str]] = ["id", "kind", "name", "nextNodeId", "taskType", "title"]

    @field_validator('id', mode="before")
    def id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[a-zA-Z0-9_-]{1,100}$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_-]{1,100}$/")
        return value

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['task']):
            raise ValueError("must be one of enum values ('task')")
        return value

    @field_validator('next_node_id', mode="before")
    def next_node_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if isinstance(value, str) and not re.match(r"^[a-zA-Z0-9_-]{1,100}$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_-]{1,100}$/")
        return value

    @field_validator('task_type')
    def task_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['call', 'manual_email', 'linkedin_profile_visit', 'linkedin_follow', 'linkedin_connection', 'linkedin_message', 'linkedin_voice', 'research', 'personalization', 'review', 'follow_up', 'other']):
            raise ValueError("must be one of enum values ('call', 'manual_email', 'linkedin_profile_visit', 'linkedin_follow', 'linkedin_connection', 'linkedin_message', 'linkedin_voice', 'research', 'personalization', 'review', 'follow_up', 'other')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailPostCadencesRequestNodesInnerAnyOf3 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailPostCadencesRequestNodesInnerAnyOf3 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "id": obj.get("id"),
            "kind": obj.get("kind"),
            "name": obj.get("name"),
            "nextNodeId": obj.get("nextNodeId"),
            "taskType": obj.get("taskType"),
            "title": obj.get("title")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


