# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from reacon_sdk.models.mail_imap_cursor import MailImapCursor
from reacon_sdk.models.mail_stored_imap_settings import MailStoredImapSettings
from reacon_sdk.models.mail_stored_smtp_settings import MailStoredSmtpSettings
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailMailboxConnectionRecord(BaseModel):
    """
    MailMailboxConnectionRecord
    """ # noqa: E501
    created_at: datetime = Field(alias="createdAt")
    credential_id: Optional[StrictStr] = Field(default=None, alias="credentialId")
    cursors: Dict[str, MailImapCursor]
    imap: Optional[MailStoredImapSettings] = None
    integration_connection_id: StrictStr = Field(alias="integrationConnectionId")
    last_error_code: Optional[StrictStr] = Field(default=None, alias="lastErrorCode")
    last_polled_at: Optional[datetime] = Field(default=None, alias="lastPolledAt")
    last_verified_at: datetime = Field(alias="lastVerifiedAt")
    mailbox_id: StrictStr = Field(alias="mailboxId")
    next_poll_at: datetime = Field(alias="nextPollAt")
    oauth_provider: Optional[StrictStr] = Field(default=None, alias="oauthProvider")
    smtp: Optional[MailStoredSmtpSettings] = None
    status: StrictStr
    tenant_id: StrictStr = Field(alias="tenantId")
    updated_at: datetime = Field(alias="updatedAt")
    version: Union[StrictFloat, StrictInt]
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["createdAt", "credentialId", "cursors", "imap", "integrationConnectionId", "lastErrorCode", "lastPolledAt", "lastVerifiedAt", "mailboxId", "nextPollAt", "oauthProvider", "smtp", "status", "tenantId", "updatedAt", "version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailMailboxConnectionRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in cursors (dict)
        _field_dict = {}
        if self.cursors:
            for _key_cursors in self.cursors:
                _field_dict[_key_cursors] = self.cursors[_key_cursors].to_dict() if self.cursors[_key_cursors] is not None else None
            _dict['cursors'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of imap
        if self.imap:
            _dict['imap'] = self.imap.to_dict()
        # override the default output from pydantic by calling `to_dict()` of smtp
        if self.smtp:
            _dict['smtp'] = self.smtp.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailMailboxConnectionRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "createdAt": obj.get("createdAt"),
            "credentialId": obj.get("credentialId"),
            "cursors": dict(
                (_k, MailImapCursor.from_dict(_v))
                for _k, _v in obj["cursors"].items()
            )
            if obj.get("cursors") is not None
            else None,
            "imap": MailStoredImapSettings.from_dict(obj["imap"]) if obj.get("imap") is not None else None,
            "integrationConnectionId": obj.get("integrationConnectionId"),
            "lastErrorCode": obj.get("lastErrorCode"),
            "lastPolledAt": obj.get("lastPolledAt"),
            "lastVerifiedAt": obj.get("lastVerifiedAt"),
            "mailboxId": obj.get("mailboxId"),
            "nextPollAt": obj.get("nextPollAt"),
            "oauthProvider": obj.get("oauthProvider"),
            "smtp": MailStoredSmtpSettings.from_dict(obj["smtp"]) if obj.get("smtp") is not None else None,
            "status": obj.get("status"),
            "tenantId": obj.get("tenantId"),
            "updatedAt": obj.get("updatedAt"),
            "version": obj.get("version")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


