# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from reacon_sdk.models.mail_post_cadences_request_nodes_inner import MailPostCadencesRequestNodesInner
from reacon_sdk.models.mail_post_cadences_request_stop_conditions import MailPostCadencesRequestStopConditions
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailPostCadencesRequest(BaseModel):
    """
    MailPostCadencesRequest
    """ # noqa: E501
    id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=200)]] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=200)]
    nodes: Annotated[List[MailPostCadencesRequestNodesInner], Field(min_length=2, max_length=500)]
    status: StrictStr
    stop_conditions: Optional[MailPostCadencesRequestStopConditions] = Field(default=None, alias="stopConditions")
    __properties: ClassVar[List[str]] = ["id", "name", "nodes", "status", "stopConditions"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['draft', 'published', 'archived']):
            raise ValueError("must be one of enum values ('draft', 'published', 'archived')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailPostCadencesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in nodes (list)
        _items = []
        if self.nodes:
            for _item_nodes in self.nodes:
                _items.append(_item_nodes.to_dict() if _item_nodes is not None else None)
            _dict['nodes'] = _items
        # override the default output from pydantic by calling `to_dict()` of stop_conditions
        if self.stop_conditions:
            _dict['stopConditions'] = self.stop_conditions.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailPostCadencesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "id": obj.get("id"),
            "name": obj.get("name"),
            "nodes": [MailPostCadencesRequestNodesInner.from_dict(_item) for _item in obj["nodes"]] if obj.get("nodes") is not None else None,
            "status": obj.get("status"),
            "stopConditions": MailPostCadencesRequestStopConditions.from_dict(obj["stopConditions"]) if obj.get("stopConditions") is not None else None
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


