# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from reacon_sdk.models.mail_signature_candidate_fields import MailSignatureCandidateFields
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailSignatureCandidate(BaseModel):
    """
    MailSignatureCandidate
    """ # noqa: E501
    confidence: Union[StrictFloat, StrictInt]
    created_at: datetime = Field(alias="createdAt")
    extractor_version: StrictStr = Field(alias="extractorVersion")
    fields: MailSignatureCandidateFields
    id: StrictStr
    signature_fingerprint: StrictStr = Field(alias="signatureFingerprint")
    signature_text: StrictStr = Field(alias="signatureText")
    signature_text_hash: StrictStr = Field(alias="signatureTextHash")
    source_message_id: StrictStr = Field(alias="sourceMessageId")
    status: StrictStr
    tenant_id: StrictStr = Field(alias="tenantId")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["confidence", "createdAt", "extractorVersion", "fields", "id", "signatureFingerprint", "signatureText", "signatureTextHash", "sourceMessageId", "status", "tenantId"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailSignatureCandidate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of fields
        if self.fields:
            _dict['fields'] = self.fields.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailSignatureCandidate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "confidence": obj.get("confidence"),
            "createdAt": obj.get("createdAt"),
            "extractorVersion": obj.get("extractorVersion"),
            "fields": MailSignatureCandidateFields.from_dict(obj["fields"]) if obj.get("fields") is not None else None,
            "id": obj.get("id"),
            "signatureFingerprint": obj.get("signatureFingerprint"),
            "signatureText": obj.get("signatureText"),
            "signatureTextHash": obj.get("signatureTextHash"),
            "sourceMessageId": obj.get("sourceMessageId"),
            "status": obj.get("status"),
            "tenantId": obj.get("tenantId")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


