# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from reacon_sdk.models.mail_post_messages_request_to import MailPostMessagesRequestTo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MailPostMessagesRequest(BaseModel):
    """
    MailPostMessagesRequest
    """ # noqa: E501
    delay_ms: Optional[Annotated[int, Field(le=31536000000, strict=True, ge=0)]] = Field(default=0, alias="delayMs")
    html: Optional[Annotated[str, Field(strict=True, max_length=500000)]] = None
    idempotency_key: Annotated[str, Field(min_length=1, strict=True, max_length=200)] = Field(alias="idempotencyKey")
    mailbox_id: Annotated[str, Field(min_length=1, strict=True, max_length=200)] = Field(alias="mailboxId")
    subject: Annotated[str, Field(min_length=1, strict=True, max_length=998)]
    text: Annotated[str, Field(min_length=1, strict=True, max_length=200000)]
    to: MailPostMessagesRequestTo
    __properties: ClassVar[List[str]] = ["delayMs", "html", "idempotencyKey", "mailboxId", "subject", "text", "to"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MailPostMessagesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of to
        if self.to:
            _dict['to'] = self.to.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MailPostMessagesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "delayMs": obj.get("delayMs") if obj.get("delayMs") is not None else 0,
            "html": obj.get("html"),
            "idempotencyKey": obj.get("idempotencyKey"),
            "mailboxId": obj.get("mailboxId"),
            "subject": obj.get("subject"),
            "text": obj.get("text"),
            "to": MailPostMessagesRequestTo.from_dict(obj["to"]) if obj.get("to") is not None else None
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


