# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, Dict, Optional
from reacon_sdk.models.product_companies_list_input import ProductCompaniesListInput
from reacon_sdk.models.product_company_delete_input import ProductCompanyDeleteInput
from reacon_sdk.models.product_company_list_add_input import ProductCompanyListAddInput
from reacon_sdk.models.product_company_track_input import ProductCompanyTrackInput
from reacon_sdk.models.product_company_update_input import ProductCompanyUpdateInput
from reacon_sdk.models.product_connected_app_push_input import ProductConnectedAppPushInput
from reacon_sdk.models.product_custom_attribute_create_input import ProductCustomAttributeCreateInput
from reacon_sdk.models.product_discover_companies_input import ProductDiscoverCompaniesInput
from reacon_sdk.models.product_discover_people_input import ProductDiscoverPeopleInput
from reacon_sdk.models.product_domain_finder_input import ProductDomainFinderInput
from reacon_sdk.models.product_email_count_input import ProductEmailCountInput
from reacon_sdk.models.product_lead_bulk_delete_input import ProductLeadBulkDeleteInput
from reacon_sdk.models.product_lead_create_input import ProductLeadCreateInput
from reacon_sdk.models.product_lead_delete_input import ProductLeadDeleteInput
from reacon_sdk.models.product_lead_get_input import ProductLeadGetInput
from reacon_sdk.models.product_lead_list_add_lead_input import ProductLeadListAddLeadInput
from reacon_sdk.models.product_lead_list_delete_input import ProductLeadListDeleteInput
from reacon_sdk.models.product_lead_list_update_input import ProductLeadListUpdateInput
from reacon_sdk.models.product_lead_tag_assign_input import ProductLeadTagAssignInput
from reacon_sdk.models.product_lead_tag_create_input import ProductLeadTagCreateInput
from reacon_sdk.models.product_lead_update_input import ProductLeadUpdateInput
from reacon_sdk.models.product_leads_list_input import ProductLeadsListInput
from reacon_sdk.models.product_person_enrich_input import ProductPersonEnrichInput
from reacon_sdk.models.product_sequence_recipient_add_input import ProductSequenceRecipientAddInput
from reacon_sdk.models.product_sequence_recipient_cancel_input import ProductSequenceRecipientCancelInput
from reacon_sdk.models.product_sequence_recipients_add_input import ProductSequenceRecipientsAddInput
from reacon_sdk.models.product_sequence_recipients_list_input import ProductSequenceRecipientsListInput
from reacon_sdk.models.product_sequence_start_input import ProductSequenceStartInput
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

PRODUCTTOOLREQUESTINPUT_ANY_OF_SCHEMAS = ["ProductCompaniesListInput", "ProductCompanyDeleteInput", "ProductCompanyListAddInput", "ProductCompanyTrackInput", "ProductCompanyUpdateInput", "ProductConnectedAppPushInput", "ProductCustomAttributeCreateInput", "ProductDiscoverCompaniesInput", "ProductDiscoverPeopleInput", "ProductDomainFinderInput", "ProductEmailCountInput", "ProductLeadBulkDeleteInput", "ProductLeadCreateInput", "ProductLeadDeleteInput", "ProductLeadGetInput", "ProductLeadListAddLeadInput", "ProductLeadListDeleteInput", "ProductLeadListUpdateInput", "ProductLeadTagAssignInput", "ProductLeadTagCreateInput", "ProductLeadUpdateInput", "ProductLeadsListInput", "ProductPersonEnrichInput", "ProductSequenceRecipientAddInput", "ProductSequenceRecipientCancelInput", "ProductSequenceRecipientsAddInput", "ProductSequenceRecipientsListInput", "ProductSequenceStartInput", "object"]

class ProductToolRequestInput(BaseModel):
    """
    Use the input model matching the tool path parameter. Equivalent input shapes appear once in this anyOf union; the tool catalog retains every named model.
    """

    # data type: ProductDiscoverCompaniesInput
    anyof_schema_1_validator: Optional[ProductDiscoverCompaniesInput] = None
    # data type: ProductDiscoverPeopleInput
    anyof_schema_2_validator: Optional[ProductDiscoverPeopleInput] = None
    # data type: ProductDomainFinderInput
    anyof_schema_3_validator: Optional[ProductDomainFinderInput] = None
    # data type: ProductEmailCountInput
    anyof_schema_4_validator: Optional[ProductEmailCountInput] = None
    # data type: ProductPersonEnrichInput
    anyof_schema_5_validator: Optional[ProductPersonEnrichInput] = None
    # data type: object
    anyof_schema_6_validator: Optional[Dict[str, Any]] = None
    # data type: ProductLeadsListInput
    anyof_schema_7_validator: Optional[ProductLeadsListInput] = None
    # data type: ProductLeadGetInput
    anyof_schema_8_validator: Optional[ProductLeadGetInput] = None
    # data type: ProductLeadCreateInput
    anyof_schema_9_validator: Optional[ProductLeadCreateInput] = None
    # data type: ProductLeadUpdateInput
    anyof_schema_10_validator: Optional[ProductLeadUpdateInput] = None
    # data type: ProductLeadDeleteInput
    anyof_schema_11_validator: Optional[ProductLeadDeleteInput] = None
    # data type: ProductLeadBulkDeleteInput
    anyof_schema_12_validator: Optional[ProductLeadBulkDeleteInput] = None
    # data type: ProductLeadTagCreateInput
    anyof_schema_13_validator: Optional[ProductLeadTagCreateInput] = None
    # data type: ProductLeadTagAssignInput
    anyof_schema_14_validator: Optional[ProductLeadTagAssignInput] = None
    # data type: ProductCustomAttributeCreateInput
    anyof_schema_15_validator: Optional[ProductCustomAttributeCreateInput] = None
    # data type: ProductLeadListUpdateInput
    anyof_schema_16_validator: Optional[ProductLeadListUpdateInput] = None
    # data type: ProductLeadListDeleteInput
    anyof_schema_17_validator: Optional[ProductLeadListDeleteInput] = None
    # data type: ProductLeadListAddLeadInput
    anyof_schema_18_validator: Optional[ProductLeadListAddLeadInput] = None
    # data type: ProductCompaniesListInput
    anyof_schema_19_validator: Optional[ProductCompaniesListInput] = None
    # data type: ProductCompanyTrackInput
    anyof_schema_20_validator: Optional[ProductCompanyTrackInput] = None
    # data type: ProductCompanyUpdateInput
    anyof_schema_21_validator: Optional[ProductCompanyUpdateInput] = None
    # data type: ProductCompanyDeleteInput
    anyof_schema_22_validator: Optional[ProductCompanyDeleteInput] = None
    # data type: ProductCompanyListAddInput
    anyof_schema_23_validator: Optional[ProductCompanyListAddInput] = None
    # data type: ProductSequenceRecipientsListInput
    anyof_schema_24_validator: Optional[ProductSequenceRecipientsListInput] = None
    # data type: ProductSequenceRecipientsAddInput
    anyof_schema_25_validator: Optional[ProductSequenceRecipientsAddInput] = None
    # data type: ProductSequenceRecipientAddInput
    anyof_schema_26_validator: Optional[ProductSequenceRecipientAddInput] = None
    # data type: ProductSequenceRecipientCancelInput
    anyof_schema_27_validator: Optional[ProductSequenceRecipientCancelInput] = None
    # data type: ProductSequenceStartInput
    anyof_schema_28_validator: Optional[ProductSequenceStartInput] = None
    # data type: ProductConnectedAppPushInput
    anyof_schema_29_validator: Optional[ProductConnectedAppPushInput] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[ProductCompaniesListInput, ProductCompanyDeleteInput, ProductCompanyListAddInput, ProductCompanyTrackInput, ProductCompanyUpdateInput, ProductConnectedAppPushInput, ProductCustomAttributeCreateInput, ProductDiscoverCompaniesInput, ProductDiscoverPeopleInput, ProductDomainFinderInput, ProductEmailCountInput, ProductLeadBulkDeleteInput, ProductLeadCreateInput, ProductLeadDeleteInput, ProductLeadGetInput, ProductLeadListAddLeadInput, ProductLeadListDeleteInput, ProductLeadListUpdateInput, ProductLeadTagAssignInput, ProductLeadTagCreateInput, ProductLeadUpdateInput, ProductLeadsListInput, ProductPersonEnrichInput, ProductSequenceRecipientAddInput, ProductSequenceRecipientCancelInput, ProductSequenceRecipientsAddInput, ProductSequenceRecipientsListInput, ProductSequenceStartInput, object]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "ProductCompaniesListInput", "ProductCompanyDeleteInput", "ProductCompanyListAddInput", "ProductCompanyTrackInput", "ProductCompanyUpdateInput", "ProductConnectedAppPushInput", "ProductCustomAttributeCreateInput", "ProductDiscoverCompaniesInput", "ProductDiscoverPeopleInput", "ProductDomainFinderInput", "ProductEmailCountInput", "ProductLeadBulkDeleteInput", "ProductLeadCreateInput", "ProductLeadDeleteInput", "ProductLeadGetInput", "ProductLeadListAddLeadInput", "ProductLeadListDeleteInput", "ProductLeadListUpdateInput", "ProductLeadTagAssignInput", "ProductLeadTagCreateInput", "ProductLeadUpdateInput", "ProductLeadsListInput", "ProductPersonEnrichInput", "ProductSequenceRecipientAddInput", "ProductSequenceRecipientCancelInput", "ProductSequenceRecipientsAddInput", "ProductSequenceRecipientsListInput", "ProductSequenceStartInput", "object" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = ProductToolRequestInput.model_construct()
        error_messages = []
        # validate data type: ProductDiscoverCompaniesInput
        if not isinstance(v, ProductDiscoverCompaniesInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductDiscoverCompaniesInput`")
        else:
            return v

        # validate data type: ProductDiscoverPeopleInput
        if not isinstance(v, ProductDiscoverPeopleInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductDiscoverPeopleInput`")
        else:
            return v

        # validate data type: ProductDomainFinderInput
        if not isinstance(v, ProductDomainFinderInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductDomainFinderInput`")
        else:
            return v

        # validate data type: ProductEmailCountInput
        if not isinstance(v, ProductEmailCountInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductEmailCountInput`")
        else:
            return v

        # validate data type: ProductPersonEnrichInput
        if not isinstance(v, ProductPersonEnrichInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductPersonEnrichInput`")
        else:
            return v

        # validate data type: object
        try:
            instance.anyof_schema_6_validator = v
            return v
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # validate data type: ProductLeadsListInput
        if not isinstance(v, ProductLeadsListInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductLeadsListInput`")
        else:
            return v

        # validate data type: ProductLeadGetInput
        if not isinstance(v, ProductLeadGetInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductLeadGetInput`")
        else:
            return v

        # validate data type: ProductLeadCreateInput
        if not isinstance(v, ProductLeadCreateInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductLeadCreateInput`")
        else:
            return v

        # validate data type: ProductLeadUpdateInput
        if not isinstance(v, ProductLeadUpdateInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductLeadUpdateInput`")
        else:
            return v

        # validate data type: ProductLeadDeleteInput
        if not isinstance(v, ProductLeadDeleteInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductLeadDeleteInput`")
        else:
            return v

        # validate data type: ProductLeadBulkDeleteInput
        if not isinstance(v, ProductLeadBulkDeleteInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductLeadBulkDeleteInput`")
        else:
            return v

        # validate data type: ProductLeadTagCreateInput
        if not isinstance(v, ProductLeadTagCreateInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductLeadTagCreateInput`")
        else:
            return v

        # validate data type: ProductLeadTagAssignInput
        if not isinstance(v, ProductLeadTagAssignInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductLeadTagAssignInput`")
        else:
            return v

        # validate data type: ProductCustomAttributeCreateInput
        if not isinstance(v, ProductCustomAttributeCreateInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductCustomAttributeCreateInput`")
        else:
            return v

        # validate data type: ProductLeadListUpdateInput
        if not isinstance(v, ProductLeadListUpdateInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductLeadListUpdateInput`")
        else:
            return v

        # validate data type: ProductLeadListDeleteInput
        if not isinstance(v, ProductLeadListDeleteInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductLeadListDeleteInput`")
        else:
            return v

        # validate data type: ProductLeadListAddLeadInput
        if not isinstance(v, ProductLeadListAddLeadInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductLeadListAddLeadInput`")
        else:
            return v

        # validate data type: ProductCompaniesListInput
        if not isinstance(v, ProductCompaniesListInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductCompaniesListInput`")
        else:
            return v

        # validate data type: ProductCompanyTrackInput
        if not isinstance(v, ProductCompanyTrackInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductCompanyTrackInput`")
        else:
            return v

        # validate data type: ProductCompanyUpdateInput
        if not isinstance(v, ProductCompanyUpdateInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductCompanyUpdateInput`")
        else:
            return v

        # validate data type: ProductCompanyDeleteInput
        if not isinstance(v, ProductCompanyDeleteInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductCompanyDeleteInput`")
        else:
            return v

        # validate data type: ProductCompanyListAddInput
        if not isinstance(v, ProductCompanyListAddInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductCompanyListAddInput`")
        else:
            return v

        # validate data type: ProductSequenceRecipientsListInput
        if not isinstance(v, ProductSequenceRecipientsListInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductSequenceRecipientsListInput`")
        else:
            return v

        # validate data type: ProductSequenceRecipientsAddInput
        if not isinstance(v, ProductSequenceRecipientsAddInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductSequenceRecipientsAddInput`")
        else:
            return v

        # validate data type: ProductSequenceRecipientAddInput
        if not isinstance(v, ProductSequenceRecipientAddInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductSequenceRecipientAddInput`")
        else:
            return v

        # validate data type: ProductSequenceRecipientCancelInput
        if not isinstance(v, ProductSequenceRecipientCancelInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductSequenceRecipientCancelInput`")
        else:
            return v

        # validate data type: ProductSequenceStartInput
        if not isinstance(v, ProductSequenceStartInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductSequenceStartInput`")
        else:
            return v

        # validate data type: ProductConnectedAppPushInput
        if not isinstance(v, ProductConnectedAppPushInput):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ProductConnectedAppPushInput`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in ProductToolRequestInput with anyOf schemas: ProductCompaniesListInput, ProductCompanyDeleteInput, ProductCompanyListAddInput, ProductCompanyTrackInput, ProductCompanyUpdateInput, ProductConnectedAppPushInput, ProductCustomAttributeCreateInput, ProductDiscoverCompaniesInput, ProductDiscoverPeopleInput, ProductDomainFinderInput, ProductEmailCountInput, ProductLeadBulkDeleteInput, ProductLeadCreateInput, ProductLeadDeleteInput, ProductLeadGetInput, ProductLeadListAddLeadInput, ProductLeadListDeleteInput, ProductLeadListUpdateInput, ProductLeadTagAssignInput, ProductLeadTagCreateInput, ProductLeadUpdateInput, ProductLeadsListInput, ProductPersonEnrichInput, ProductSequenceRecipientAddInput, ProductSequenceRecipientCancelInput, ProductSequenceRecipientsAddInput, ProductSequenceRecipientsListInput, ProductSequenceStartInput, object. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[ProductDiscoverCompaniesInput] = None
        try:
            instance.actual_instance = ProductDiscoverCompaniesInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[ProductDiscoverPeopleInput] = None
        try:
            instance.actual_instance = ProductDiscoverPeopleInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[ProductDomainFinderInput] = None
        try:
            instance.actual_instance = ProductDomainFinderInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[ProductEmailCountInput] = None
        try:
            instance.actual_instance = ProductEmailCountInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[ProductPersonEnrichInput] = None
        try:
            instance.actual_instance = ProductPersonEnrichInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # deserialize data into object
        try:
            # validation
            instance.anyof_schema_6_validator = json.loads(json_str)
            # assign value to actual_instance
            instance.actual_instance = instance.anyof_schema_6_validator
            return instance
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # anyof_schema_7_validator: Optional[ProductLeadsListInput] = None
        try:
            instance.actual_instance = ProductLeadsListInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_8_validator: Optional[ProductLeadGetInput] = None
        try:
            instance.actual_instance = ProductLeadGetInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_9_validator: Optional[ProductLeadCreateInput] = None
        try:
            instance.actual_instance = ProductLeadCreateInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_10_validator: Optional[ProductLeadUpdateInput] = None
        try:
            instance.actual_instance = ProductLeadUpdateInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_11_validator: Optional[ProductLeadDeleteInput] = None
        try:
            instance.actual_instance = ProductLeadDeleteInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_12_validator: Optional[ProductLeadBulkDeleteInput] = None
        try:
            instance.actual_instance = ProductLeadBulkDeleteInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_13_validator: Optional[ProductLeadTagCreateInput] = None
        try:
            instance.actual_instance = ProductLeadTagCreateInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_14_validator: Optional[ProductLeadTagAssignInput] = None
        try:
            instance.actual_instance = ProductLeadTagAssignInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_15_validator: Optional[ProductCustomAttributeCreateInput] = None
        try:
            instance.actual_instance = ProductCustomAttributeCreateInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_16_validator: Optional[ProductLeadListUpdateInput] = None
        try:
            instance.actual_instance = ProductLeadListUpdateInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_17_validator: Optional[ProductLeadListDeleteInput] = None
        try:
            instance.actual_instance = ProductLeadListDeleteInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_18_validator: Optional[ProductLeadListAddLeadInput] = None
        try:
            instance.actual_instance = ProductLeadListAddLeadInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_19_validator: Optional[ProductCompaniesListInput] = None
        try:
            instance.actual_instance = ProductCompaniesListInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_20_validator: Optional[ProductCompanyTrackInput] = None
        try:
            instance.actual_instance = ProductCompanyTrackInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_21_validator: Optional[ProductCompanyUpdateInput] = None
        try:
            instance.actual_instance = ProductCompanyUpdateInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_22_validator: Optional[ProductCompanyDeleteInput] = None
        try:
            instance.actual_instance = ProductCompanyDeleteInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_23_validator: Optional[ProductCompanyListAddInput] = None
        try:
            instance.actual_instance = ProductCompanyListAddInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_24_validator: Optional[ProductSequenceRecipientsListInput] = None
        try:
            instance.actual_instance = ProductSequenceRecipientsListInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_25_validator: Optional[ProductSequenceRecipientsAddInput] = None
        try:
            instance.actual_instance = ProductSequenceRecipientsAddInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_26_validator: Optional[ProductSequenceRecipientAddInput] = None
        try:
            instance.actual_instance = ProductSequenceRecipientAddInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_27_validator: Optional[ProductSequenceRecipientCancelInput] = None
        try:
            instance.actual_instance = ProductSequenceRecipientCancelInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_28_validator: Optional[ProductSequenceStartInput] = None
        try:
            instance.actual_instance = ProductSequenceStartInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_29_validator: Optional[ProductConnectedAppPushInput] = None
        try:
            instance.actual_instance = ProductConnectedAppPushInput.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ProductToolRequestInput with anyOf schemas: ProductCompaniesListInput, ProductCompanyDeleteInput, ProductCompanyListAddInput, ProductCompanyTrackInput, ProductCompanyUpdateInput, ProductConnectedAppPushInput, ProductCustomAttributeCreateInput, ProductDiscoverCompaniesInput, ProductDiscoverPeopleInput, ProductDomainFinderInput, ProductEmailCountInput, ProductLeadBulkDeleteInput, ProductLeadCreateInput, ProductLeadDeleteInput, ProductLeadGetInput, ProductLeadListAddLeadInput, ProductLeadListDeleteInput, ProductLeadListUpdateInput, ProductLeadTagAssignInput, ProductLeadTagCreateInput, ProductLeadUpdateInput, ProductLeadsListInput, ProductPersonEnrichInput, ProductSequenceRecipientAddInput, ProductSequenceRecipientCancelInput, ProductSequenceRecipientsAddInput, ProductSequenceRecipientsListInput, ProductSequenceStartInput, object. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ProductCompaniesListInput, ProductCompanyDeleteInput, ProductCompanyListAddInput, ProductCompanyTrackInput, ProductCompanyUpdateInput, ProductConnectedAppPushInput, ProductCustomAttributeCreateInput, ProductDiscoverCompaniesInput, ProductDiscoverPeopleInput, ProductDomainFinderInput, ProductEmailCountInput, ProductLeadBulkDeleteInput, ProductLeadCreateInput, ProductLeadDeleteInput, ProductLeadGetInput, ProductLeadListAddLeadInput, ProductLeadListDeleteInput, ProductLeadListUpdateInput, ProductLeadTagAssignInput, ProductLeadTagCreateInput, ProductLeadUpdateInput, ProductLeadsListInput, ProductPersonEnrichInput, ProductSequenceRecipientAddInput, ProductSequenceRecipientCancelInput, ProductSequenceRecipientsAddInput, ProductSequenceRecipientsListInput, ProductSequenceStartInput, object]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


