# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from reacon_sdk.models.queue_integration_lead_export_request_selection_scopes_inner import QueueIntegrationLeadExportRequestSelectionScopesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QueueIntegrationLeadExportRequest(BaseModel):
    """
    QueueIntegrationLeadExportRequest
    """ # noqa: E501
    deselected_lead_ids: Optional[Annotated[List[StrictStr], Field(max_length=10000)]] = Field(default=None, alias="deselectedLeadIds")
    lead_ids: Optional[Annotated[List[StrictStr], Field(min_length=1, max_length=10000)]] = Field(default=None, alias="leadIds")
    request_id: Optional[Annotated[str, Field(min_length=8, strict=True, max_length=220)]] = Field(default=None, alias="requestId")
    selection_scopes: Optional[Annotated[List[QueueIntegrationLeadExportRequestSelectionScopesInner], Field(max_length=1000)]] = Field(default=None, alias="selectionScopes")
    __properties: ClassVar[List[str]] = []

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueueIntegrationLeadExportRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueueIntegrationLeadExportRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


