# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from reacon_sdk.models.company_list_results_inner_addresses_inner import CompanyListResultsInnerAddressesInner
from reacon_sdk.models.update_lead_request_company import UpdateLeadRequestCompany
from reacon_sdk.models.update_lead_request_person import UpdateLeadRequestPerson
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateLeadRequest(BaseModel):
    """
    UpdateLeadRequest
    """ # noqa: E501
    company: Optional[UpdateLeadRequestCompany] = None
    company_addresses: Optional[List[CompanyListResultsInnerAddressesInner]] = None
    company_founded_on: Optional[StrictStr] = None
    company_industry: Optional[StrictStr] = None
    company_linkedin: Optional[StrictStr] = None
    company_location: Optional[StrictStr] = None
    company_name: Optional[StrictStr] = None
    company_number_of_employees: Optional[StrictInt] = None
    company_stock: Optional[StrictStr] = None
    company_twitter: Optional[StrictStr] = None
    company_type: Optional[StrictStr] = None
    company_website: Optional[StrictStr] = None
    person: Optional[UpdateLeadRequestPerson] = None
    person_first_name: Optional[StrictStr] = None
    person_last_name: Optional[StrictStr] = None
    person_lead_location: Optional[StrictStr] = None
    person_linkedin: Optional[StrictStr] = None
    person_phone_number: Optional[StrictStr] = None
    person_position: Optional[StrictStr] = None
    person_twitter: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["company", "company_addresses", "company_founded_on", "company_industry", "company_linkedin", "company_location", "company_name", "company_number_of_employees", "company_stock", "company_twitter", "company_type", "company_website", "person", "person_first_name", "person_last_name", "person_lead_location", "person_linkedin", "person_phone_number", "person_position", "person_twitter", "tags"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateLeadRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # override the default output from pydantic by calling `to_dict()` of company
        if self.company:
            _dict['company'] = self.company.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in company_addresses (list)
        _items = []
        if self.company_addresses:
            for _item_company_addresses in self.company_addresses:
                _items.append(_item_company_addresses.to_dict() if _item_company_addresses is not None else None)
            _dict['company_addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of person
        if self.person:
            _dict['person'] = self.person.to_dict()
        # set to None if company_addresses (nullable) is None
        # and model_fields_set contains the field
        if self.company_addresses is None and "company_addresses" in self.model_fields_set:
            _dict['company_addresses'] = None

        # set to None if company_founded_on (nullable) is None
        # and model_fields_set contains the field
        if self.company_founded_on is None and "company_founded_on" in self.model_fields_set:
            _dict['company_founded_on'] = None

        # set to None if company_industry (nullable) is None
        # and model_fields_set contains the field
        if self.company_industry is None and "company_industry" in self.model_fields_set:
            _dict['company_industry'] = None

        # set to None if company_linkedin (nullable) is None
        # and model_fields_set contains the field
        if self.company_linkedin is None and "company_linkedin" in self.model_fields_set:
            _dict['company_linkedin'] = None

        # set to None if company_location (nullable) is None
        # and model_fields_set contains the field
        if self.company_location is None and "company_location" in self.model_fields_set:
            _dict['company_location'] = None

        # set to None if company_name (nullable) is None
        # and model_fields_set contains the field
        if self.company_name is None and "company_name" in self.model_fields_set:
            _dict['company_name'] = None

        # set to None if company_number_of_employees (nullable) is None
        # and model_fields_set contains the field
        if self.company_number_of_employees is None and "company_number_of_employees" in self.model_fields_set:
            _dict['company_number_of_employees'] = None

        # set to None if company_stock (nullable) is None
        # and model_fields_set contains the field
        if self.company_stock is None and "company_stock" in self.model_fields_set:
            _dict['company_stock'] = None

        # set to None if company_twitter (nullable) is None
        # and model_fields_set contains the field
        if self.company_twitter is None and "company_twitter" in self.model_fields_set:
            _dict['company_twitter'] = None

        # set to None if company_type (nullable) is None
        # and model_fields_set contains the field
        if self.company_type is None and "company_type" in self.model_fields_set:
            _dict['company_type'] = None

        # set to None if company_website (nullable) is None
        # and model_fields_set contains the field
        if self.company_website is None and "company_website" in self.model_fields_set:
            _dict['company_website'] = None

        # set to None if person_first_name (nullable) is None
        # and model_fields_set contains the field
        if self.person_first_name is None and "person_first_name" in self.model_fields_set:
            _dict['person_first_name'] = None

        # set to None if person_last_name (nullable) is None
        # and model_fields_set contains the field
        if self.person_last_name is None and "person_last_name" in self.model_fields_set:
            _dict['person_last_name'] = None

        # set to None if person_lead_location (nullable) is None
        # and model_fields_set contains the field
        if self.person_lead_location is None and "person_lead_location" in self.model_fields_set:
            _dict['person_lead_location'] = None

        # set to None if person_linkedin (nullable) is None
        # and model_fields_set contains the field
        if self.person_linkedin is None and "person_linkedin" in self.model_fields_set:
            _dict['person_linkedin'] = None

        # set to None if person_phone_number (nullable) is None
        # and model_fields_set contains the field
        if self.person_phone_number is None and "person_phone_number" in self.model_fields_set:
            _dict['person_phone_number'] = None

        # set to None if person_position (nullable) is None
        # and model_fields_set contains the field
        if self.person_position is None and "person_position" in self.model_fields_set:
            _dict['person_position'] = None

        # set to None if person_twitter (nullable) is None
        # and model_fields_set contains the field
        if self.person_twitter is None and "person_twitter" in self.model_fields_set:
            _dict['person_twitter'] = None

        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateLeadRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "company": UpdateLeadRequestCompany.from_dict(obj["company"]) if obj.get("company") is not None else None,
            "company_addresses": [CompanyListResultsInnerAddressesInner.from_dict(_item) for _item in obj["company_addresses"]] if obj.get("company_addresses") is not None else None,
            "company_founded_on": obj.get("company_founded_on"),
            "company_industry": obj.get("company_industry"),
            "company_linkedin": obj.get("company_linkedin"),
            "company_location": obj.get("company_location"),
            "company_name": obj.get("company_name"),
            "company_number_of_employees": obj.get("company_number_of_employees"),
            "company_stock": obj.get("company_stock"),
            "company_twitter": obj.get("company_twitter"),
            "company_type": obj.get("company_type"),
            "company_website": obj.get("company_website"),
            "person": UpdateLeadRequestPerson.from_dict(obj["person"]) if obj.get("person") is not None else None,
            "person_first_name": obj.get("person_first_name"),
            "person_last_name": obj.get("person_last_name"),
            "person_lead_location": obj.get("person_lead_location"),
            "person_linkedin": obj.get("person_linkedin"),
            "person_phone_number": obj.get("person_phone_number"),
            "person_position": obj.get("person_position"),
            "person_twitter": obj.get("person_twitter"),
            "tags": obj.get("tags")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        return _obj


