# coding: utf-8

"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class VerificationProgress(BaseModel):
    """
    VerificationProgress
    """ # noqa: E501
    capability_epoch: Optional[StrictInt] = Field(default=None, alias="capabilityEpoch")
    greylist_attempt: Optional[StrictInt] = Field(default=None, alias="greylistAttempt")
    invalidation_reason: Optional[StrictStr] = Field(default=None, alias="invalidationReason")
    mx_fingerprint: Optional[StrictStr] = Field(default=None, alias="mxFingerprint")
    next_retry_at: Optional[datetime] = Field(default=None, alias="nextRetryAt")
    preferred_ip: Optional[StrictStr] = Field(default=None, alias="preferredIp")
    reputation_generation: Optional[StrictInt] = Field(default=None, alias="reputationGeneration")
    request_id: StrictStr = Field(alias="requestId")
    required_tier: Optional[StrictStr] = Field(default=None, description="Known values: clean, dirty. Clients preserve future values.", alias="requiredTier")
    state: StrictStr = Field(description="Known values: queued, processing. Clients preserve future values.")
    updated_at: datetime = Field(alias="updatedAt")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["capabilityEpoch", "greylistAttempt", "invalidationReason", "mxFingerprint", "nextRetryAt", "preferredIp", "reputationGeneration", "requestId", "requiredTier", "state", "updatedAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VerificationProgress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
            exclude_unset=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VerificationProgress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _data = {
            "capabilityEpoch": obj.get("capabilityEpoch"),
            "greylistAttempt": obj.get("greylistAttempt"),
            "invalidationReason": obj.get("invalidationReason"),
            "mxFingerprint": obj.get("mxFingerprint"),
            "nextRetryAt": obj.get("nextRetryAt"),
            "preferredIp": obj.get("preferredIp"),
            "reputationGeneration": obj.get("reputationGeneration"),
            "requestId": obj.get("requestId"),
            "requiredTier": obj.get("requiredTier"),
            "state": obj.get("state"),
            "updatedAt": obj.get("updatedAt")
        }
        _obj = cls.model_validate({key: value for key, value in _data.items() if key in obj})
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


