"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "reacon-sdk"
VERSION = "0.1.0b1"
PYTHON_REQUIRES = ">= 3.10"
REQUIRES = [
    "httpx-sse == 0.4.3",
    "python-dateutil >= 2.8.2",
    "httpx >= 0.28.1",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Reacon API",
    author="Reacon",
    author_email="achazal@reacon.io",
    url="https://github.com/reacon-io/reacon-python",
    keywords=["OpenAPI", "OpenAPI-Generator", "Reacon API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache-2.0",
    long_description_content_type='text/markdown',
    long_description="""\
    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
    """,  # noqa: E501
    package_data={"reacon_sdk": ["py.typed"]},
)
