"""
    Reacon API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import StrictStr, field_validator
from typing import Optional
from reacon_sdk.models.name_patterns_response import NamePatternsResponse
from reacon_sdk.models.name_verification_response import NameVerificationResponse

from reacon_sdk.api_client import ApiClient, RequestSerialized
from reacon_sdk.api_response import ApiResponse
from reacon_sdk.rest import RESTResponseType
from reacon_sdk.sync_helper import run_sync


class NamesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    async def list_name_patterns(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NamePatternsResponse:
        """List supported email name patterns

        Returns name patterns ranked by score. domain is required and validated; optional first and last query fields do not alter this static pattern list.

        :param domain: (required)
        :type domain: str
        :param first:
        :type first: str
        :param last:
        :type last: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_name_patterns_serialize(
            domain=domain,
            first=first,
            last=last,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NamePatternsResponse",
            '400': "ApiError",
            '401': "ApiError",
            '403': "ApiError",
            '429': "ApiError",
            '500': "ApiError",
            'default': "ApiError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _retry=_retry, _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def list_name_patterns_with_http_info(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NamePatternsResponse]:
        """List supported email name patterns

        Returns name patterns ranked by score. domain is required and validated; optional first and last query fields do not alter this static pattern list.

        :param domain: (required)
        :type domain: str
        :param first:
        :type first: str
        :param last:
        :type last: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_name_patterns_serialize(
            domain=domain,
            first=first,
            last=last,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NamePatternsResponse",
            '400': "ApiError",
            '401': "ApiError",
            '403': "ApiError",
            '429': "ApiError",
            '500': "ApiError",
            'default': "ApiError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _retry=_retry, _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def list_name_patterns_without_preload_content(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List supported email name patterns

        Returns name patterns ranked by score. domain is required and validated; optional first and last query fields do not alter this static pattern list.

        :param domain: (required)
        :type domain: str
        :param first:
        :type first: str
        :param last:
        :type last: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_name_patterns_serialize(
            domain=domain,
            first=first,
            last=last,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NamePatternsResponse",
            '400': "ApiError",
            '401': "ApiError",
            '403': "ApiError",
            '429': "ApiError",
            '500': "ApiError",
            'default': "ApiError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _retry=_retry, _request_timeout=_request_timeout
        )
        return response_data.response


    @validate_call
    def list_name_patterns_sync(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NamePatternsResponse:
        """List supported email name patterns (synchronous)

        Synchronous variant of :meth:`list_name_patterns`. It calls the asynchronous
        method and blocks until it completes.
        """ # noqa: E501
        return run_sync(
            self.list_name_patterns(
                domain=domain,
                first=first,
                last=last,
                _retry=_retry, _request_timeout=_request_timeout,
                _request_auth=_request_auth,
                _content_type=_content_type,
                _headers=_headers,
                _host_index=_host_index,
            )
        )


    @validate_call
    def list_name_patterns_sync_with_http_info(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NamePatternsResponse]:
        """List supported email name patterns (synchronous)

        Synchronous variant of :meth:`list_name_patterns_with_http_info`. It calls the
        asynchronous method and blocks until it completes.
        """ # noqa: E501
        return run_sync(
            self.list_name_patterns_with_http_info(
                domain=domain,
                first=first,
                last=last,
                _retry=_retry, _request_timeout=_request_timeout,
                _request_auth=_request_auth,
                _content_type=_content_type,
                _headers=_headers,
                _host_index=_host_index,
            )
        )


    @validate_call
    def list_name_patterns_sync_without_preload_content(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List supported email name patterns (synchronous)

        Synchronous variant of :meth:`list_name_patterns_without_preload_content`. It calls
        the asynchronous method and blocks until it completes.
        """ # noqa: E501
        return run_sync(
            self.list_name_patterns_without_preload_content(
                domain=domain,
                first=first,
                last=last,
                _retry=_retry, _request_timeout=_request_timeout,
                _request_auth=_request_auth,
                _content_type=_content_type,
                _headers=_headers,
                _host_index=_host_index,
            )
        )


    def _list_name_patterns_serialize(
        self,
        domain,
        first,
        last,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if domain is not None:
            
            _query_params.append(('domain', domain))
            
        if first is not None:
            
            _query_params.append(('first', first))
            
        if last is not None:
            
            _query_params.append(('last', last))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/name/schemas',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def verify_name(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        cache_max_age: Optional[StrictStr] = None,
        only_if_free: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NameVerificationResponse:
        """Verify name-based email patterns

        Verifies candidate addresses built from sanitized first and last names. JSON returns patterns, globalStages and results. With Accept: text/event-stream, events contain stages or individual pattern verdicts; ordinary completion is clean EOF, with no aggregate final marker. When no candidates can be built, the stream instead emits a result envelope and ends. Errors can describe individual candidates; an error event is not universally terminal. The operation may consume credits; never reconnect or replay automatically.

        :param domain: (required)
        :type domain: str
        :param first:
        :type first: str
        :param last:
        :type last: str
        :param cache_max_age:
        :type cache_max_age: str
        :param only_if_free:
        :type only_if_free: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._verify_name_serialize(
            domain=domain,
            first=first,
            last=last,
            cache_max_age=cache_max_age,
            only_if_free=only_if_free,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NameVerificationResponse",
            '400': "ApiError",
            '401': "ApiError",
            '402': "ApiError",
            '403': "ApiError",
            '422': "ApiError",
            '429': "ApiError",
            '500': "ApiError",
            'default': "ApiError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _retry=_retry, _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def verify_name_with_http_info(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        cache_max_age: Optional[StrictStr] = None,
        only_if_free: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NameVerificationResponse]:
        """Verify name-based email patterns

        Verifies candidate addresses built from sanitized first and last names. JSON returns patterns, globalStages and results. With Accept: text/event-stream, events contain stages or individual pattern verdicts; ordinary completion is clean EOF, with no aggregate final marker. When no candidates can be built, the stream instead emits a result envelope and ends. Errors can describe individual candidates; an error event is not universally terminal. The operation may consume credits; never reconnect or replay automatically.

        :param domain: (required)
        :type domain: str
        :param first:
        :type first: str
        :param last:
        :type last: str
        :param cache_max_age:
        :type cache_max_age: str
        :param only_if_free:
        :type only_if_free: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._verify_name_serialize(
            domain=domain,
            first=first,
            last=last,
            cache_max_age=cache_max_age,
            only_if_free=only_if_free,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NameVerificationResponse",
            '400': "ApiError",
            '401': "ApiError",
            '402': "ApiError",
            '403': "ApiError",
            '422': "ApiError",
            '429': "ApiError",
            '500': "ApiError",
            'default': "ApiError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _retry=_retry, _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def verify_name_without_preload_content(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        cache_max_age: Optional[StrictStr] = None,
        only_if_free: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Verify name-based email patterns

        Verifies candidate addresses built from sanitized first and last names. JSON returns patterns, globalStages and results. With Accept: text/event-stream, events contain stages or individual pattern verdicts; ordinary completion is clean EOF, with no aggregate final marker. When no candidates can be built, the stream instead emits a result envelope and ends. Errors can describe individual candidates; an error event is not universally terminal. The operation may consume credits; never reconnect or replay automatically.

        :param domain: (required)
        :type domain: str
        :param first:
        :type first: str
        :param last:
        :type last: str
        :param cache_max_age:
        :type cache_max_age: str
        :param only_if_free:
        :type only_if_free: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._verify_name_serialize(
            domain=domain,
            first=first,
            last=last,
            cache_max_age=cache_max_age,
            only_if_free=only_if_free,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "NameVerificationResponse",
            '400': "ApiError",
            '401': "ApiError",
            '402': "ApiError",
            '403': "ApiError",
            '422': "ApiError",
            '429': "ApiError",
            '500': "ApiError",
            'default': "ApiError",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _retry=_retry, _request_timeout=_request_timeout
        )
        return response_data.response


    @validate_call
    def verify_name_sync(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        cache_max_age: Optional[StrictStr] = None,
        only_if_free: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> NameVerificationResponse:
        """Verify name-based email patterns (synchronous)

        Synchronous variant of :meth:`verify_name`. It calls the asynchronous
        method and blocks until it completes.
        """ # noqa: E501
        return run_sync(
            self.verify_name(
                domain=domain,
                first=first,
                last=last,
                cache_max_age=cache_max_age,
                only_if_free=only_if_free,
                _retry=_retry, _request_timeout=_request_timeout,
                _request_auth=_request_auth,
                _content_type=_content_type,
                _headers=_headers,
                _host_index=_host_index,
            )
        )


    @validate_call
    def verify_name_sync_with_http_info(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        cache_max_age: Optional[StrictStr] = None,
        only_if_free: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[NameVerificationResponse]:
        """Verify name-based email patterns (synchronous)

        Synchronous variant of :meth:`verify_name_with_http_info`. It calls the
        asynchronous method and blocks until it completes.
        """ # noqa: E501
        return run_sync(
            self.verify_name_with_http_info(
                domain=domain,
                first=first,
                last=last,
                cache_max_age=cache_max_age,
                only_if_free=only_if_free,
                _retry=_retry, _request_timeout=_request_timeout,
                _request_auth=_request_auth,
                _content_type=_content_type,
                _headers=_headers,
                _host_index=_host_index,
            )
        )


    @validate_call
    def verify_name_sync_without_preload_content(
        self,
        domain: StrictStr,
        first: Optional[StrictStr] = None,
        last: Optional[StrictStr] = None,
        cache_max_age: Optional[StrictStr] = None,
        only_if_free: Optional[StrictStr] = None,
        _retry: Any = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Verify name-based email patterns (synchronous)

        Synchronous variant of :meth:`verify_name_without_preload_content`. It calls
        the asynchronous method and blocks until it completes.
        """ # noqa: E501
        return run_sync(
            self.verify_name_without_preload_content(
                domain=domain,
                first=first,
                last=last,
                cache_max_age=cache_max_age,
                only_if_free=only_if_free,
                _retry=_retry, _request_timeout=_request_timeout,
                _request_auth=_request_auth,
                _content_type=_content_type,
                _headers=_headers,
                _host_index=_host_index,
            )
        )


    def _verify_name_serialize(
        self,
        domain,
        first,
        last,
        cache_max_age,
        only_if_free,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if domain is not None:
            
            _query_params.append(('domain', domain))
            
        if first is not None:
            
            _query_params.append(('first', first))
            
        if last is not None:
            
            _query_params.append(('last', last))
            
        if cache_max_age is not None:
            
            _query_params.append(('cacheMaxAge', cache_max_age))
            
        if only_if_free is not None:
            
            _query_params.append(('onlyIfFree', only_if_free))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'ApiKey'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/name/verify',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


